insert into product_category (id, name, description) values (-1, 'Juline Bissett', 'nibh ligula nec sem duis');
insert into product_category (id, name, description) values (-2, 'Ninetta James', 'convallis eget eleifend luctus ultricies eu');
insert into product_category (id, name, description) values (-3, 'June Campa', 'mauris lacinia sapien quis libero nullam');
insert into product_category (id, name, description) values (-4, 'Rubia Oliveras', 'posuere cubilia curae nulla dapibus');
insert into product_category (id, name, description) values (-5, 'Juliane Vigors', 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus');
insert into product_category (id, name, description) values (-6, 'Amber Spataro', 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque');
insert into product_category (id, name, description) values (-7, 'Ivonne Rawstorne', 'tristique est et tempus semper est');
insert into product_category (id, name, description) values (-8, 'Ada Kleine', 'augue a suscipit nulla elit ac nulla');
insert into product_category (id, name, description) values (-9, 'Phylys Wyldes', 'ante ipsum primis in faucibus');
insert into product_category (id, name, description) values (-10, 'Traci Croasdale', 'aliquam erat volutpat in congue etiam');
insert into product_category (id, name, description) values (-11, 'Kristina Brake', 'eget tincidunt eget tempus vel');
insert into product_category (id, name, description) values (-12, 'Bo Tramel', 'a libero nam dui proin');
insert into product_category (id, name, description) values (-13, 'Rona Venners', 'donec vitae nisi nam ultrices libero non');
insert into product_category (id, name, description) values (-14, 'Kile Sutton', 'at velit eu est congue elementum in');
insert into product_category (id, name, description) values (-15, 'Harmonie Cottill', 'id mauris vulputate elementum nullam varius nulla facilisi');
insert into product_category (id, name, description) values (-16, 'Vivyan Gwyllt', 'imperdiet nullam orci pede venenatis');
insert into product_category (id, name, description) values (-17, 'Gnni Hodge', 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl');
insert into product_category (id, name, description) values (-18, 'Camala Chasier', 'interdum in ante vestibulum ante ipsum primis in');
insert into product_category (id, name, description) values (-19, 'Cati Fellgate', 'eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan');
insert into product_category (id, name, description) values (-20, 'Shannon Hempel', 'ultrices enim lorem ipsum dolor');
insert into product_category (id, name, description) values (-21, 'Bordie Matteo', 'etiam faucibus cursus urna ut tellus nulla');
insert into product_category (id, name, description) values (-22, 'Eunice Behning', 'sit amet consectetuer adipiscing elit');
insert into product_category (id, name, description) values (-23, 'Yelena Cartner', 'nulla ac enim in tempor');
insert into product_category (id, name, description) values (-24, 'Ileana Dumper', 'cubilia curae mauris viverra diam vitae quam suspendisse');
insert into product_category (id, name, description) values (-25, 'Richmond Flancinbaum', 'maecenas leo odio condimentum id');
insert into product_category (id, name, description) values (-26, 'Trudie Wise', 'nunc viverra dapibus nulla suscipit ligula in lacus');
insert into product_category (id, name, description) values (-27, 'Jamima Margaret', 'nisi vulputate nonummy maecenas tincidunt lacus at velit');
insert into product_category (id, name, description) values (-28, 'Earlie Sturt', 'ligula vehicula consequat morbi a ipsum integer a');
insert into product_category (id, name, description) values (-29, 'Vlad Bogeys', 'ultrices erat tortor sollicitudin mi sit amet');
insert into product_category (id, name, description) values (-30, 'Bobbye Druce', 'vestibulum velit id pretium iaculis diam erat fermentum justo');
insert into product_category (id, name, description) values (-31, 'Cassandra Noe', 'ultricies eu nibh quisque id justo sit');
insert into product_category (id, name, description) values (-32, 'Isabelle Antoszewski', 'cursus urna ut tellus nulla');
insert into product_category (id, name, description) values (-33, 'Peggi Doughty', 'volutpat erat quisque erat eros viverra eget');
insert into product_category (id, name, description) values (-34, 'Karon Santus', 'sociis natoque penatibus et magnis dis parturient montes nascetur');
insert into product_category (id, name, description) values (-35, 'Ev Beininck', 'arcu sed augue aliquam erat volutpat in congue');
insert into product_category (id, name, description) values (-36, 'Val Flew', 'interdum eu tincidunt in leo maecenas');
insert into product_category (id, name, description) values (-37, 'Rayner Turvey', 'eget massa tempor convallis nulla neque');
insert into product_category (id, name, description) values (-38, 'Lynsey Ducham', 'vel augue vestibulum ante ipsum primis in faucibus orci luctus');
insert into product_category (id, name, description) values (-39, 'Gussie Crennan', 'laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui');
insert into product_category (id, name, description) values (-40, 'Johna Kellen', 'odio consequat varius integer ac leo pellentesque');
insert into product_category (id, name, description) values (-41, 'Neddie Allwood', 'curabitur at ipsum ac tellus semper');
insert into product_category (id, name, description) values (-42, 'Slade Tessyman', 'ac tellus semper interdum mauris ullamcorper purus sit amet nulla');
insert into product_category (id, name, description) values (-43, 'Kile Pinke', 'scelerisque mauris sit amet eros suspendisse accumsan');
insert into product_category (id, name, description) values (-44, 'Tye Vedmore', 'luctus tincidunt nulla mollis molestie lorem quisque ut');
insert into product_category (id, name, description) values (-45, 'Filide Lidyard', 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec');
insert into product_category (id, name, description) values (-46, 'Micheal Drohan', 'nulla eget eros elementum pellentesque quisque porta volutpat erat');
insert into product_category (id, name, description) values (-47, 'Barby Figgins', 'vestibulum ante ipsum primis in faucibus orci luctus');
insert into product_category (id, name, description) values (-48, 'Bessy MacClinton', 'amet turpis elementum ligula vehicula consequat morbi a ipsum');
insert into product_category (id, name, description) values (-49, 'Casi Adshed', 'in consequat ut nulla sed');
insert into product_category (id, name, description) values (-50, 'Mitchell Babin', 'in purus eu magna vulputate luctus cum sociis natoque penatibus');
insert into product_category (id, name, description) values (-51, 'Alexis Bucknall', 'justo in blandit ultrices enim lorem ipsum');
insert into product_category (id, name, description) values (-52, 'Bernadene Keelan', 'at lorem integer tincidunt ante vel ipsum praesent');
insert into product_category (id, name, description) values (-53, 'Garwin Morse', 'ligula nec sem duis aliquam convallis nunc');
insert into product_category (id, name, description) values (-54, 'Prudy Flobert', 'non mauris morbi non lectus aliquam sit amet diam in');
insert into product_category (id, name, description) values (-55, 'Madonna Loffhead', 'suscipit a feugiat et eros vestibulum ac est lacinia nisi');
insert into product_category (id, name, description) values (-56, 'Annaliese Iggalden', 'arcu adipiscing molestie hendrerit at vulputate');
insert into product_category (id, name, description) values (-57, 'Dacey Oley', 'nisi nam ultrices libero non mattis pulvinar nulla');
insert into product_category (id, name, description) values (-58, 'Gawain Trainer', 'quam sollicitudin vitae consectetuer eget rutrum at lorem integer');
insert into product_category (id, name, description) values (-59, 'Jocelyn Chansonnau', 'sollicitudin vitae consectetuer eget rutrum at');
insert into product_category (id, name, description) values (-60, 'Sutton Wiper', 'urna pretium nisl ut volutpat sapien arcu sed augue aliquam');
insert into product_category (id, name, description) values (-61, 'Devlen Elwyn', 'integer aliquet massa id lobortis convallis');
insert into product_category (id, name, description) values (-62, 'Isador Smee', 'sed sagittis nam congue risus semper porta volutpat quam');
insert into product_category (id, name, description) values (-63, 'Dan Andrivot', 'nisl nunc rhoncus dui vel sem');
insert into product_category (id, name, description) values (-64, 'Erich Hebbes', 'tincidunt eu felis fusce posuere felis sed lacus morbi');
insert into product_category (id, name, description) values (-65, 'Sheila Burrows', 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros');
insert into product_category (id, name, description) values (-66, 'Lorrie Forsdicke', 'nec dui luctus rutrum nulla tellus in sagittis');
insert into product_category (id, name, description) values (-67, 'Fraze Ellerman', 'suscipit ligula in lacus curabitur at ipsum');
insert into product_category (id, name, description) values (-68, 'Latrena Barwack', 'risus semper porta volutpat quam pede lobortis ligula sit');
insert into product_category (id, name, description) values (-69, 'Cordula Pavy', 'neque duis bibendum morbi non quam');
insert into product_category (id, name, description) values (-70, 'Doy Dabbes', 'nulla integer pede justo lacinia eget');
insert into product_category (id, name, description) values (-71, 'Rickert Weathers', 'dolor vel est donec odio justo sollicitudin ut');
insert into product_category (id, name, description) values (-72, 'Quinlan Devaney', 'praesent id massa id nisl venenatis lacinia aenean sit');
insert into product_category (id, name, description) values (-73, 'Clare Fishby', 'praesent lectus vestibulum quam sapien varius ut');
insert into product_category (id, name, description) values (-74, 'Rosalinde Clissett', 'nunc rhoncus dui vel sem sed');
insert into product_category (id, name, description) values (-75, 'Pietrek Poate', 'id consequat in consequat ut nulla sed accumsan felis ut');
insert into product_category (id, name, description) values (-76, 'Joey Joontjes', 'tincidunt eget tempus vel pede morbi');
insert into product_category (id, name, description) values (-77, 'Morgen Duckels', 'tristique fusce congue diam id ornare imperdiet sapien urna pretium');
insert into product_category (id, name, description) values (-78, 'Margo Simenel', 'aliquam non mauris morbi non lectus aliquam sit amet');
insert into product_category (id, name, description) values (-79, 'Allyson Ricker', 'faucibus orci luctus et ultrices posuere cubilia');
insert into product_category (id, name, description) values (-80, 'Lorena Whittle', 'pretium iaculis justo in hac habitasse platea dictumst etiam');
insert into product_category (id, name, description) values (-81, 'Raeann Tripney', 'eros vestibulum ac est lacinia nisi venenatis tristique');
insert into product_category (id, name, description) values (-82, 'Reyna Ormrod', 'vel nisl duis ac nibh fusce lacus');
insert into product_category (id, name, description) values (-83, 'Humberto Eisold', 'nibh in quis justo maecenas rhoncus aliquam lacus morbi quis');
insert into product_category (id, name, description) values (-84, 'Cory Littlemore', 'erat tortor sollicitudin mi sit amet');
insert into product_category (id, name, description) values (-85, 'Kandace Briereton', 'nulla suscipit ligula in lacus curabitur at ipsum ac');
insert into product_category (id, name, description) values (-86, 'Caroline Yarwood', 'cras mi pede malesuada in imperdiet');
insert into product_category (id, name, description) values (-87, 'Rhoda Liveley', 'donec quis orci eget orci vehicula condimentum curabitur');
insert into product_category (id, name, description) values (-88, 'Nancee Breadmore', 'non pretium quis lectus suspendisse potenti');
insert into product_category (id, name, description) values (-89, 'Winslow Moncreiffe', 'ut at dolor quis odio');
insert into product_category (id, name, description) values (-90, 'Sherm de''-Ancy Willis', 'dolor sit amet consectetuer adipiscing elit');
insert into product_category (id, name, description) values (-91, 'Bev Wellan', 'sociis natoque penatibus et magnis dis parturient montes');
insert into product_category (id, name, description) values (-92, 'Genni Wapol', 'volutpat dui maecenas tristique est');
insert into product_category (id, name, description) values (-93, 'Tandie Follis', 'orci vehicula condimentum curabitur in libero');
insert into product_category (id, name, description) values (-94, 'Damaris Corcut', 'volutpat sapien arcu sed augue');
insert into product_category (id, name, description) values (-95, 'Agretha Derry', 'duis ac nibh fusce lacus');
insert into product_category (id, name, description) values (-96, 'Chaim Van Hault', 'molestie lorem quisque ut erat');
insert into product_category (id, name, description) values (-97, 'Donella Dillinger', 'ultrices posuere cubilia curae mauris viverra');
insert into product_category (id, name, description) values (-98, 'Gretta Bartoleyn', 'vulputate nonummy maecenas tincidunt lacus at');
insert into product_category (id, name, description) values (-99, 'Aldis Seleway', 'duis bibendum morbi non quam nec');
insert into product_category (id, name, description) values (-100, 'Trixie Brewitt', 'purus aliquet at feugiat non pretium quis lectus');
insert into product_category (id, name, description) values (-101, 'Nickie Sizzey', 'risus semper porta volutpat quam pede lobortis');
insert into product_category (id, name, description) values (-102, 'Syd MacTague', 'nec sem duis aliquam convallis nunc');
insert into product_category (id, name, description) values (-103, 'Elyse Yetton', 'ut dolor morbi vel lectus in quam fringilla rhoncus');
insert into product_category (id, name, description) values (-104, 'Bogey Few', 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis');
insert into product_category (id, name, description) values (-105, 'Thornton Cowgill', 'vestibulum proin eu mi nulla ac enim in tempor turpis');
insert into product_category (id, name, description) values (-106, 'Vinson Chicken', 'a libero nam dui proin leo odio porttitor');
insert into product_category (id, name, description) values (-107, 'Burlie MacKeig', 'praesent blandit lacinia erat vestibulum');
insert into product_category (id, name, description) values (-108, 'Pancho Keynd', 'aliquet ultrices erat tortor sollicitudin mi sit');
insert into product_category (id, name, description) values (-109, 'Brand Kears', 'turpis adipiscing lorem vitae mattis nibh ligula');
insert into product_category (id, name, description) values (-110, 'Marybeth Pizey', 'dui luctus rutrum nulla tellus in sagittis');
insert into product_category (id, name, description) values (-111, 'Pepi Willmott', 'porttitor lacus at turpis donec');
insert into product_category (id, name, description) values (-112, 'Merry Marlin', 'morbi vestibulum velit id pretium iaculis diam');
insert into product_category (id, name, description) values (-113, 'Codie Puttrell', 'faucibus accumsan odio curabitur convallis');
insert into product_category (id, name, description) values (-114, 'Galvan Eadie', 'ligula in lacus curabitur at');
insert into product_category (id, name, description) values (-115, 'Randie Espadero', 'id massa id nisl venenatis');
insert into product_category (id, name, description) values (-116, 'Emilee Sugar', 'luctus ultricies eu nibh quisque id');
insert into product_category (id, name, description) values (-117, 'Andres Clinnick', 'vel augue vestibulum ante ipsum primis in');
insert into product_category (id, name, description) values (-118, 'Daphene Cuncliffe', 'pulvinar nulla pede ullamcorper augue');
insert into product_category (id, name, description) values (-119, 'Ivett Abbate', 'lorem vitae mattis nibh ligula nec sem duis');
insert into product_category (id, name, description) values (-120, 'Padget Ruperto', 'nisl ut volutpat sapien arcu sed augue aliquam');
insert into product_category (id, name, description) values (-121, 'Marco Hubner', 'a feugiat et eros vestibulum');
insert into product_category (id, name, description) values (-122, 'Torrence Batrop', 'blandit nam nulla integer pede justo lacinia eget tincidunt');
insert into product_category (id, name, description) values (-123, 'Regan Cisneros', 'in imperdiet et commodo vulputate');
insert into product_category (id, name, description) values (-124, 'Fielding Palmar', 'nulla suspendisse potenti cras in purus eu magna');
insert into product_category (id, name, description) values (-125, 'Ketti Burbidge', 'mi sit amet lobortis sapien sapien non mi integer ac');
insert into product_category (id, name, description) values (-126, 'Udale Leakner', 'accumsan tellus nisi eu orci mauris');
insert into product_category (id, name, description) values (-127, 'Emma Haslock', 'ipsum dolor sit amet consectetuer adipiscing elit proin');
insert into product_category (id, name, description) values (-128, 'Allison Daily', 'in porttitor pede justo eu massa');
insert into product_category (id, name, description) values (-129, 'Joanna Cranshaw', 'in magna bibendum imperdiet nullam orci');
insert into product_category (id, name, description) values (-130, 'Padgett Ordidge', 'eu est congue elementum in');
insert into product_category (id, name, description) values (-131, 'Randy Sustins', 'venenatis non sodales sed tincidunt eu');
insert into product_category (id, name, description) values (-132, 'Shantee Plitz', 'blandit non interdum in ante vestibulum');
insert into product_category (id, name, description) values (-133, 'Quentin Vassie', 'eget congue eget semper rutrum nulla nunc purus phasellus');
insert into product_category (id, name, description) values (-134, 'Sigismondo Gambles', 'viverra dapibus nulla suscipit ligula in lacus curabitur');
insert into product_category (id, name, description) values (-135, 'Stefania Stile', 'suspendisse ornare consequat lectus in est risus auctor');
insert into product_category (id, name, description) values (-136, 'Tybi Pettit', 'accumsan tortor quis turpis sed');
insert into product_category (id, name, description) values (-137, 'Corinna Adriaens', 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum');
insert into product_category (id, name, description) values (-138, 'Krissie Tomkys', 'sed justo pellentesque viverra pede ac diam');
insert into product_category (id, name, description) values (-139, 'Newton Slimings', 'suspendisse potenti in eleifend quam');
insert into product_category (id, name, description) values (-140, 'Izzy Martineau', 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra');
insert into product_category (id, name, description) values (-141, 'Meryl Cupitt', 'nunc vestibulum ante ipsum primis');
insert into product_category (id, name, description) values (-142, 'Urson Benettolo', 'vestibulum aliquet ultrices erat tortor sollicitudin mi sit');
insert into product_category (id, name, description) values (-143, 'Timothy Girvan', 'posuere cubilia curae duis faucibus accumsan odio curabitur');
insert into product_category (id, name, description) values (-144, 'Murdock Ohm', 'vehicula condimentum curabitur in libero ut massa volutpat convallis');
insert into product_category (id, name, description) values (-145, 'Sonnie Borchardt', 'sem duis aliquam convallis nunc proin');
insert into product_category (id, name, description) values (-146, 'Max Kilshaw', 'eros elementum pellentesque quisque porta volutpat erat quisque');
insert into product_category (id, name, description) values (-147, 'Audi Garnsworth', 'adipiscing elit proin risus praesent lectus vestibulum quam sapien varius');
insert into product_category (id, name, description) values (-148, 'Sylas Wandtke', 'ipsum primis in faucibus orci luctus');
insert into product_category (id, name, description) values (-149, 'Bernadette Pretious', 'nullam varius nulla facilisi cras non');
insert into product_category (id, name, description) values (-150, 'Hollyanne Lindeberg', 'risus dapibus augue vel accumsan tellus nisi eu orci');
insert into product_category (id, name, description) values (-151, 'Amelie Delacourt', 'sit amet consectetuer adipiscing elit');
insert into product_category (id, name, description) values (-152, 'Auria Castanos', 'ac neque duis bibendum morbi non quam nec dui');
insert into product_category (id, name, description) values (-153, 'Melessa Sealove', 'vel ipsum praesent blandit lacinia erat vestibulum sed');
insert into product_category (id, name, description) values (-154, 'Micky Mingardo', 'odio cras mi pede malesuada in imperdiet et commodo');
insert into product_category (id, name, description) values (-155, 'Gaby VanBrugh', 'mauris sit amet eros suspendisse accumsan');
insert into product_category (id, name, description) values (-156, 'Emelia Ledgister', 'fringilla rhoncus mauris enim leo rhoncus');
insert into product_category (id, name, description) values (-157, 'Jayson Waything', 'posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices');
insert into product_category (id, name, description) values (-158, 'Roy Jeavons', 'accumsan odio curabitur convallis duis consequat');
insert into product_category (id, name, description) values (-159, 'Todd Fincken', 'sapien iaculis congue vivamus metus arcu adipiscing molestie');
insert into product_category (id, name, description) values (-160, 'Nikoletta Hembrow', 'mauris lacinia sapien quis libero');
insert into product_category (id, name, description) values (-161, 'Marlee Shrimpling', 'dui nec nisi volutpat eleifend donec ut dolor morbi');
insert into product_category (id, name, description) values (-162, 'Chiquia Affuso', 'duis bibendum morbi non quam nec dui luctus rutrum');
insert into product_category (id, name, description) values (-163, 'Adelle Patriskson', 'lobortis est phasellus sit amet erat');
insert into product_category (id, name, description) values (-164, 'Rorie Pendlington', 'justo nec condimentum neque sapien placerat ante nulla justo aliquam');
insert into product_category (id, name, description) values (-165, 'Pippa Whitney', 'in ante vestibulum ante ipsum primis in faucibus orci');
insert into product_category (id, name, description) values (-166, 'Buffy Cogley', 'condimentum curabitur in libero ut massa volutpat');
insert into product_category (id, name, description) values (-167, 'Lissi Gershom', 'maecenas rhoncus aliquam lacus morbi quis');
insert into product_category (id, name, description) values (-168, 'Ailey Abdon', 'massa id nisl venenatis lacinia aenean');
insert into product_category (id, name, description) values (-169, 'Lazarus Kitchinham', 'nunc rhoncus dui vel sem');
insert into product_category (id, name, description) values (-170, 'Kelvin Baynes', 'velit eu est congue elementum in hac habitasse');
insert into product_category (id, name, description) values (-171, 'Jackqueline Saffell', 'aliquam lacus morbi quis tortor id');
insert into product_category (id, name, description) values (-172, 'Wayne Kundt', 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum');
insert into product_category (id, name, description) values (-173, 'Eddie Mirrlees', 'semper interdum mauris ullamcorper purus sit amet nulla quisque');
insert into product_category (id, name, description) values (-174, 'Hillary Hansell', 'vitae quam suspendisse potenti nullam porttitor');
insert into product_category (id, name, description) values (-175, 'Darnall Howle', 'ornare consequat lectus in est risus auctor sed');
insert into product_category (id, name, description) values (-176, 'Ruperta Clipston', 'nec euismod scelerisque quam turpis');
insert into product_category (id, name, description) values (-177, 'Friedrick Dablin', 'praesent lectus vestibulum quam sapien varius ut blandit non');
insert into product_category (id, name, description) values (-178, 'Rey Filippozzi', 'tortor id nulla ultrices aliquet');
insert into product_category (id, name, description) values (-179, 'Peria Dutteridge', 'integer tincidunt ante vel ipsum praesent blandit lacinia erat');
insert into product_category (id, name, description) values (-180, 'Hilarius Brogini', 'non velit donec diam neque vestibulum eget vulputate ut ultrices');
insert into product_category (id, name, description) values (-181, 'Sarene Hasney', 'turpis integer aliquet massa id lobortis');
insert into product_category (id, name, description) values (-182, 'Maribeth Geydon', 'nulla ultrices aliquet maecenas leo odio condimentum id luctus nec');
insert into product_category (id, name, description) values (-183, 'Marje Laing', 'quam nec dui luctus rutrum nulla tellus in');
insert into product_category (id, name, description) values (-184, 'Homer Curner', 'bibendum felis sed interdum venenatis turpis enim blandit');
insert into product_category (id, name, description) values (-185, 'Kyla Garatty', 'est risus auctor sed tristique in tempus');
insert into product_category (id, name, description) values (-186, 'Gerri Figliovanni', 'nulla dapibus dolor vel est donec odio');
insert into product_category (id, name, description) values (-187, 'Ced Rosenzwig', 'interdum mauris ullamcorper purus sit amet');
insert into product_category (id, name, description) values (-188, 'Layney Londors', 'lacinia aenean sit amet justo morbi ut odio cras');
insert into product_category (id, name, description) values (-189, 'Zea Skipperbottom', 'vulputate luctus cum sociis natoque penatibus et magnis dis parturient');
insert into product_category (id, name, description) values (-190, 'Barn Cullivan', 'duis aliquam convallis nunc proin at turpis');
insert into product_category (id, name, description) values (-191, 'Tedmund Shulver', 'tempus vel pede morbi porttitor lorem id');
insert into product_category (id, name, description) values (-192, 'Abba Downton', 'turpis donec posuere metus vitae ipsum aliquam non mauris');
insert into product_category (id, name, description) values (-193, 'Tanitansy Vacher', 'amet cursus id turpis integer');
insert into product_category (id, name, description) values (-194, 'Arron Rodriguez', 'vel nulla eget eros elementum pellentesque quisque porta');
insert into product_category (id, name, description) values (-195, 'Kay Lanmeid', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into product_category (id, name, description) values (-196, 'Halsey Vigar', 'posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat');
insert into product_category (id, name, description) values (-197, 'Lillian Dunbobin', 'auctor sed tristique in tempus sit amet');
insert into product_category (id, name, description) values (-198, 'Ulrika Cosgrive', 'odio consequat varius integer ac leo');
insert into product_category (id, name, description) values (-199, 'Tomasine Glynn', 'orci luctus et ultrices posuere cubilia');
insert into product_category (id, name, description) values (-200, 'Clary Barthrop', 'tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida');
insert into product_category (id, name, description) values (-201, 'Beilul Sneddon', 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc');
insert into product_category (id, name, description) values (-202, 'Nana Mountlow', 'nibh fusce lacus purus aliquet at feugiat');
insert into product_category (id, name, description) values (-203, 'Bernice Setchfield', 'augue a suscipit nulla elit ac nulla sed vel enim');
insert into product_category (id, name, description) values (-204, 'Guntar Wearn', 'lorem ipsum dolor sit amet consectetuer adipiscing');
insert into product_category (id, name, description) values (-205, 'Silvain Brazier', 'mi nulla ac enim in tempor turpis nec euismod');
insert into product_category (id, name, description) values (-206, 'Reta Coweuppe', 'velit eu est congue elementum in hac habitasse platea');
insert into product_category (id, name, description) values (-207, 'Reg Hammelberg', 'convallis tortor risus dapibus augue');
insert into product_category (id, name, description) values (-208, 'Chrissie Stradling', 'elementum in hac habitasse platea dictumst morbi vestibulum velit');
insert into product_category (id, name, description) values (-209, 'Neala Halahan', 'fusce posuere felis sed lacus');
insert into product_category (id, name, description) values (-210, 'Mignonne Rickhuss', 'velit nec nisi vulputate nonummy maecenas tincidunt');
insert into product_category (id, name, description) values (-211, 'Maxwell Franciskiewicz', 'cum sociis natoque penatibus et magnis dis');
insert into product_category (id, name, description) values (-212, 'Zach Atcheson', 'cursus urna ut tellus nulla ut erat');
insert into product_category (id, name, description) values (-213, 'Nicolas Jaeggi', 'aenean fermentum donec ut mauris eget massa');
insert into product_category (id, name, description) values (-214, 'Annora Atter', 'at nunc commodo placerat praesent blandit nam');
insert into product_category (id, name, description) values (-215, 'Rowe Jakubovicz', 'quisque ut erat curabitur gravida nisi');
insert into product_category (id, name, description) values (-216, 'Marsiella Dewhurst', 'in blandit ultrices enim lorem');
insert into product_category (id, name, description) values (-217, 'Elfreda Arnaudi', 'at turpis donec posuere metus vitae');
insert into product_category (id, name, description) values (-218, 'Leia McPartlin', 'sapien urna pretium nisl ut volutpat sapien arcu sed augue');
insert into product_category (id, name, description) values (-219, 'Marika Sanchez', 'luctus et ultrices posuere cubilia curae donec');
insert into product_category (id, name, description) values (-220, 'Caddric Druhan', 'cursus id turpis integer aliquet');
insert into product_category (id, name, description) values (-221, 'Isabeau Dryden', 'donec quis orci eget orci vehicula condimentum curabitur in');
insert into product_category (id, name, description) values (-222, 'Cello Kiltie', 'ultrices vel augue vestibulum ante');
insert into product_category (id, name, description) values (-223, 'Tasha Alvaro', 'sapien placerat ante nulla justo aliquam quis turpis eget elit');
insert into product_category (id, name, description) values (-224, 'Kelby Echalie', 'sapien urna pretium nisl ut volutpat sapien');
insert into product_category (id, name, description) values (-225, 'Cliff Fleckney', 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida');
insert into product_category (id, name, description) values (-226, 'Cherry Alderwick', 'fusce posuere felis sed lacus morbi sem');
insert into product_category (id, name, description) values (-227, 'Aloisia Ashburner', 'sed vel enim sit amet nunc viverra dapibus nulla');
insert into product_category (id, name, description) values (-228, 'Ernesta Loftin', 'lacinia aenean sit amet justo morbi');
insert into product_category (id, name, description) values (-229, 'Kaylee Caffin', 'lorem vitae mattis nibh ligula');
insert into product_category (id, name, description) values (-230, 'Rebeca Rudge', 'tortor risus dapibus augue vel accumsan tellus');
insert into product_category (id, name, description) values (-231, 'Antonetta Likly', 'velit nec nisi vulputate nonummy maecenas tincidunt');
insert into product_category (id, name, description) values (-232, 'Hastings Burnhard', 'dui vel sem sed sagittis nam congue risus');
insert into product_category (id, name, description) values (-233, 'Anthe Baine', 'diam id ornare imperdiet sapien urna pretium nisl ut');
insert into product_category (id, name, description) values (-234, 'Leticia Cogdon', 'dapibus duis at velit eu est congue elementum in hac');
insert into product_category (id, name, description) values (-235, 'Margie Bellenger', 'at turpis donec posuere metus vitae');
insert into product_category (id, name, description) values (-236, 'Terrye Devorill', 'pellentesque ultrices phasellus id sapien in sapien');
insert into product_category (id, name, description) values (-237, 'Caterina Itzcak', 'magna at nunc commodo placerat praesent blandit nam nulla');
insert into product_category (id, name, description) values (-238, 'Danit Ussher', 'nascetur ridiculus mus etiam vel augue');
insert into product_category (id, name, description) values (-239, 'Guillema Wingeat', 'lorem vitae mattis nibh ligula nec sem duis aliquam');
insert into product_category (id, name, description) values (-240, 'Trevar Kopisch', 'at dolor quis odio consequat');
insert into product_category (id, name, description) values (-241, 'Sander Goranov', 'dolor vel est donec odio justo sollicitudin ut');
insert into product_category (id, name, description) values (-242, 'Marris Spaducci', 'posuere nonummy integer non velit donec diam neque vestibulum eget');
insert into product_category (id, name, description) values (-243, 'Jeremy Fensome', 'sodales scelerisque mauris sit amet');
insert into product_category (id, name, description) values (-244, 'Dilan Gowthorpe', 'molestie lorem quisque ut erat');
insert into product_category (id, name, description) values (-245, 'Manya Cheale', 'luctus et ultrices posuere cubilia curae duis faucibus accumsan');
insert into product_category (id, name, description) values (-246, 'Haley Jacke', 'natoque penatibus et magnis dis parturient montes');
insert into product_category (id, name, description) values (-247, 'Simona Stuke', 'amet eleifend pede libero quis');
insert into product_category (id, name, description) values (-248, 'Dodie Huckell', 'hendrerit at vulputate vitae nisl aenean lectus pellentesque eget');
insert into product_category (id, name, description) values (-249, 'Giana Dundon', 'quam sapien varius ut blandit non interdum');
insert into product_category (id, name, description) values (-250, 'Gratia Skeermer', 'lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar');
insert into product_category (id, name, description) values (-251, 'Burton Zavattieri', 'quam a odio in hac');
insert into product_category (id, name, description) values (-252, 'Abie Mersh', 'blandit lacinia erat vestibulum sed magna at nunc');
insert into product_category (id, name, description) values (-253, 'Ronnie Cuel', 'nulla dapibus dolor vel est donec odio justo sollicitudin');
insert into product_category (id, name, description) values (-254, 'Codi Dubarry', 'vestibulum sagittis sapien cum sociis natoque penatibus');
insert into product_category (id, name, description) values (-255, 'Nathaniel Latehouse', 'aliquet maecenas leo odio condimentum id luctus nec molestie sed');
insert into product_category (id, name, description) values (-256, 'Albert Panton', 'in porttitor pede justo eu massa donec dapibus duis at');
insert into product_category (id, name, description) values (-257, 'Leanna Truder', 'primis in faucibus orci luctus et ultrices');
insert into product_category (id, name, description) values (-258, 'Suzy Laurenz', 'venenatis tristique fusce congue diam');
insert into product_category (id, name, description) values (-259, 'Ibrahim Dightham', 'ac nulla sed vel enim sit amet');
insert into product_category (id, name, description) values (-260, 'Dahlia Mooreed', 'porttitor id consequat in consequat ut nulla');
insert into product_category (id, name, description) values (-261, 'Magdalena Yablsley', 'odio consequat varius integer ac leo pellentesque ultrices');
insert into product_category (id, name, description) values (-262, 'Jacky Hatchard', 'proin eu mi nulla ac enim in tempor turpis');
insert into product_category (id, name, description) values (-263, 'Selma Gawke', 'porttitor lacus at turpis donec posuere metus vitae');
insert into product_category (id, name, description) values (-264, 'Delano Ridel', 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor');
insert into product_category (id, name, description) values (-265, 'Nady Aldwick', 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit');
insert into product_category (id, name, description) values (-266, 'Jacquetta Doorbar', 'amet eleifend pede libero quis');
insert into product_category (id, name, description) values (-267, 'Mirna Pinck', 'lacinia aenean sit amet justo morbi ut');
insert into product_category (id, name, description) values (-268, 'Jozef Cardo', 'orci luctus et ultrices posuere cubilia');
insert into product_category (id, name, description) values (-269, 'Sutton Corteis', 'mattis odio donec vitae nisi nam ultrices libero non mattis');
insert into product_category (id, name, description) values (-270, 'Petr Dunbobbin', 'neque sapien placerat ante nulla justo aliquam quis turpis');
insert into product_category (id, name, description) values (-271, 'Linnet Birkenshaw', 'cras pellentesque volutpat dui maecenas tristique est et tempus semper');
insert into product_category (id, name, description) values (-272, 'Elmo Jinkin', 'leo pellentesque ultrices mattis odio donec vitae');
insert into product_category (id, name, description) values (-273, 'Eleanor Longmead', 'mi pede malesuada in imperdiet et commodo vulputate justo');
insert into product_category (id, name, description) values (-274, 'Ganny Clayson', 'natoque penatibus et magnis dis parturient montes');
insert into product_category (id, name, description) values (-275, 'Cinda Savoury', 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc');
insert into product_category (id, name, description) values (-276, 'Olia Hartil', 'primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into product_category (id, name, description) values (-277, 'Patrizia Pales', 'aliquet ultrices erat tortor sollicitudin mi sit amet');
insert into product_category (id, name, description) values (-278, 'Dani Ewebank', 'at feugiat non pretium quis lectus suspendisse potenti in');
insert into product_category (id, name, description) values (-279, 'Felipe Levis', 'neque aenean auctor gravida sem praesent id massa id');
insert into product_category (id, name, description) values (-280, 'Ebba Rolinson', 'porta volutpat quam pede lobortis');
insert into product_category (id, name, description) values (-281, 'Ahmad Lechelle', 'lacus morbi sem mauris laoreet ut');
insert into product_category (id, name, description) values (-282, 'Leora Ferentz', 'nonummy integer non velit donec');
insert into product_category (id, name, description) values (-283, 'Camila McRobb', 'dui vel nisl duis ac nibh fusce lacus purus');
insert into product_category (id, name, description) values (-284, 'Romain Lyal', 'nonummy integer non velit donec diam neque vestibulum eget vulputate');
insert into product_category (id, name, description) values (-285, 'Fletcher Stanbrooke', 'velit donec diam neque vestibulum eget vulputate ut ultrices vel');
insert into product_category (id, name, description) values (-286, 'Thaddus Dreossi', 'ut tellus nulla ut erat id mauris vulputate elementum');
insert into product_category (id, name, description) values (-287, 'Temple Dannel', 'in leo maecenas pulvinar lobortis est phasellus sit amet erat');
insert into product_category (id, name, description) values (-288, 'Faulkner Harriman', 'sem praesent id massa id nisl venenatis');
insert into product_category (id, name, description) values (-289, 'Desi Stileman', 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus');
insert into product_category (id, name, description) values (-290, 'Caye Oldford', 'pellentesque at nulla suspendisse potenti cras in');
insert into product_category (id, name, description) values (-291, 'Cedric Pavolini', 'tincidunt eget tempus vel pede morbi porttitor lorem id ligula');
insert into product_category (id, name, description) values (-292, 'Ethelda Hellis', 'ornare consequat lectus in est risus auctor sed');
insert into product_category (id, name, description) values (-293, 'Kial Feldheim', 'interdum mauris ullamcorper purus sit');
insert into product_category (id, name, description) values (-294, 'Wallis Gonneau', 'pede venenatis non sodales sed');
insert into product_category (id, name, description) values (-295, 'Selle Toolin', 'ligula vehicula consequat morbi a');
insert into product_category (id, name, description) values (-296, 'Bernarr Navarre', 'tortor risus dapibus augue vel accumsan');
insert into product_category (id, name, description) values (-297, 'Bella Dinning', 'nisl aenean lectus pellentesque eget nunc donec');
insert into product_category (id, name, description) values (-298, 'Teriann Oxley', 'in felis donec semper sapien a libero nam');
insert into product_category (id, name, description) values (-299, 'Jonathan Busse', 'vulputate vitae nisl aenean lectus pellentesque');
insert into product_category (id, name, description) values (-300, 'Ollie Mewton', 'nullam sit amet turpis elementum ligula');
insert into product_category (id, name, description) values (-301, 'Elora Matteucci', 'ante ipsum primis in faucibus orci luctus');
insert into product_category (id, name, description) values (-302, 'Brooks Swiggs', 'velit vivamus vel nulla eget eros elementum');
insert into product_category (id, name, description) values (-303, 'Hetty Whetland', 'dui maecenas tristique est et tempus semper est quam pharetra');
insert into product_category (id, name, description) values (-304, 'Ginny Clashe', 'diam cras pellentesque volutpat dui maecenas tristique est et');
insert into product_category (id, name, description) values (-305, 'Conrade Allum', 'in tempor turpis nec euismod scelerisque');
insert into product_category (id, name, description) values (-306, 'Giraldo McOwen', 'id ligula suspendisse ornare consequat');
insert into product_category (id, name, description) values (-307, 'Missie Benck', 'hac habitasse platea dictumst etiam faucibus cursus urna');
insert into product_category (id, name, description) values (-308, 'Garek Simoes', 'potenti nullam porttitor lacus at turpis donec posuere metus');
insert into product_category (id, name, description) values (-309, 'Griffin Crayton', 'eget massa tempor convallis nulla neque libero convallis eget');
insert into product_category (id, name, description) values (-310, 'Vernor McKintosh', 'rutrum rutrum neque aenean auctor');
insert into product_category (id, name, description) values (-311, 'Shena Heliot', 'vestibulum aliquet ultrices erat tortor sollicitudin mi');
insert into product_category (id, name, description) values (-312, 'Bartholemy Kordes', 'nec molestie sed justo pellentesque viverra pede');
insert into product_category (id, name, description) values (-313, 'Zsa zsa Pentelow', 'nibh in hac habitasse platea dictumst aliquam augue quam');
insert into product_category (id, name, description) values (-314, 'Minnie Freear', 'posuere cubilia curae donec pharetra');
insert into product_category (id, name, description) values (-315, 'Berti Whitwell', 'vivamus vel nulla eget eros elementum pellentesque quisque porta');
insert into product_category (id, name, description) values (-316, 'Ibby Mamwell', 'velit id pretium iaculis diam erat');
insert into product_category (id, name, description) values (-317, 'Grenville Ianiello', 'in blandit ultrices enim lorem ipsum dolor sit amet');
insert into product_category (id, name, description) values (-318, 'Vincenty Gore', 'mi pede malesuada in imperdiet et');
insert into product_category (id, name, description) values (-319, 'Ethel Clineck', 'in hac habitasse platea dictumst morbi vestibulum');
insert into product_category (id, name, description) values (-320, 'Dorree Portigall', 'ultrices erat tortor sollicitudin mi sit amet');
insert into product_category (id, name, description) values (-321, 'Noel Cassey', 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin risus');
insert into product_category (id, name, description) values (-322, 'Stevie Burnand', 'dui nec nisi volutpat eleifend donec ut dolor morbi vel');
insert into product_category (id, name, description) values (-323, 'Hobey Chittie', 'tempus vivamus in felis eu sapien cursus');
insert into product_category (id, name, description) values (-324, 'Ardisj Bleasdille', 'nec molestie sed justo pellentesque');
insert into product_category (id, name, description) values (-325, 'Penni Raphael', 'arcu sed augue aliquam erat');
insert into product_category (id, name, description) values (-326, 'Mayor Ailmer', 'vel augue vestibulum ante ipsum primis in faucibus orci');
insert into product_category (id, name, description) values (-327, 'Ibby Jacks', 'phasellus sit amet erat nulla tempus vivamus');
insert into product_category (id, name, description) values (-328, 'Christoforo Rockliffe', 'odio curabitur convallis duis consequat dui nec nisi volutpat');
insert into product_category (id, name, description) values (-329, 'Debi Donizeau', 'luctus et ultrices posuere cubilia curae donec');
insert into product_category (id, name, description) values (-330, 'Lorraine Rastrick', 'pellentesque at nulla suspendisse potenti cras in');
insert into product_category (id, name, description) values (-331, 'Elysee Bartolomeu', 'rutrum nulla tellus in sagittis dui vel');
insert into product_category (id, name, description) values (-332, 'Ivie Darbon', 'et ultrices posuere cubilia curae donec pharetra magna');
insert into product_category (id, name, description) values (-333, 'Patrizio Ellington', 'potenti in eleifend quam a odio in hac habitasse platea');
insert into product_category (id, name, description) values (-334, 'Kathie Impey', 'vulputate ut ultrices vel augue vestibulum');
insert into product_category (id, name, description) values (-335, 'Tommie Nazareth', 'lacinia eget tincidunt eget tempus');
insert into product_category (id, name, description) values (-336, 'Janelle Doddemeade', 'urna ut tellus nulla ut erat');
insert into product_category (id, name, description) values (-337, 'Alice Glyne', 'pede justo eu massa donec dapibus');
insert into product_category (id, name, description) values (-338, 'Bond Borrett', 'in tempus sit amet sem fusce');
insert into product_category (id, name, description) values (-339, 'Forster MacAnellye', 'nulla dapibus dolor vel est donec odio justo');
insert into product_category (id, name, description) values (-340, 'Jackie Milne', 'nunc proin at turpis a pede posuere nonummy');
insert into product_category (id, name, description) values (-341, 'Thor Grocutt', 'nisi eu orci mauris lacinia sapien quis libero nullam');
insert into product_category (id, name, description) values (-342, 'Rupert Torbeck', 'tristique est et tempus semper est quam pharetra magna ac');
insert into product_category (id, name, description) values (-343, 'Noe Manderson', 'eget vulputate ut ultrices vel augue vestibulum ante ipsum');
insert into product_category (id, name, description) values (-344, 'Jaine Raphael', 'diam in magna bibendum imperdiet nullam orci pede venenatis non');
insert into product_category (id, name, description) values (-345, 'Kathryne Lafflin', 'lectus suspendisse potenti in eleifend quam a');
insert into product_category (id, name, description) values (-346, 'Cristiano Flucker', 'vestibulum ac est lacinia nisi venenatis');
insert into product_category (id, name, description) values (-347, 'Skyler Lamburn', 'integer a nibh in quis justo');
insert into product_category (id, name, description) values (-348, 'Sunny Anstis', 'ornare imperdiet sapien urna pretium');
insert into product_category (id, name, description) values (-349, 'Simone Coldicott', 'luctus et ultrices posuere cubilia curae nulla dapibus dolor vel');
insert into product_category (id, name, description) values (-350, 'Karoly Cadlock', 'condimentum neque sapien placerat ante');
insert into product_category (id, name, description) values (-351, 'Terri Girtin', 'justo sollicitudin ut suscipit a feugiat et eros vestibulum');
insert into product_category (id, name, description) values (-352, 'Flossi Saiger', 'odio in hac habitasse platea dictumst');
insert into product_category (id, name, description) values (-353, 'Rani Foat', 'vestibulum sagittis sapien cum sociis');
insert into product_category (id, name, description) values (-354, 'Fernande Crowd', 'iaculis justo in hac habitasse platea dictumst etiam faucibus');
insert into product_category (id, name, description) values (-355, 'Palm Lound', 'posuere cubilia curae mauris viverra diam vitae quam suspendisse');
insert into product_category (id, name, description) values (-356, 'Clem Singyard', 'mi nulla ac enim in tempor turpis nec euismod');
insert into product_category (id, name, description) values (-357, 'Umeko Ambroz', 'a odio in hac habitasse platea dictumst');
insert into product_category (id, name, description) values (-358, 'Cassey Rasor', 'ante vel ipsum praesent blandit lacinia erat vestibulum');
insert into product_category (id, name, description) values (-359, 'Tonye Grigori', 'eget tempus vel pede morbi porttitor');
insert into product_category (id, name, description) values (-360, 'Fergus Stern', 'sed lacus morbi sem mauris laoreet ut');
insert into product_category (id, name, description) values (-361, 'Hillary Phillimore', 'dolor sit amet consectetuer adipiscing elit proin interdum mauris non');
insert into product_category (id, name, description) values (-362, 'Aldrich Pasek', 'vestibulum sit amet cursus id turpis integer');
insert into product_category (id, name, description) values (-363, 'Hendrick Solon', 'pede lobortis ligula sit amet eleifend');
insert into product_category (id, name, description) values (-364, 'Johna Kiley', 'consequat varius integer ac leo');
insert into product_category (id, name, description) values (-365, 'Matilde Kornousek', 'ligula sit amet eleifend pede libero quis orci');
insert into product_category (id, name, description) values (-366, 'Solomon Freestone', 'vestibulum quam sapien varius ut blandit non interdum in');
insert into product_category (id, name, description) values (-367, 'Dorothee Heggman', 'eu magna vulputate luctus cum sociis');
insert into product_category (id, name, description) values (-368, 'Wylma McVee', 'vehicula condimentum curabitur in libero ut massa volutpat');
insert into product_category (id, name, description) values (-369, 'Fania Flux', 'vivamus vel nulla eget eros elementum pellentesque');
insert into product_category (id, name, description) values (-370, 'Pris Hellwich', 'venenatis lacinia aenean sit amet justo morbi ut odio');
insert into product_category (id, name, description) values (-371, 'Sophronia Simeons', 'tincidunt eu felis fusce posuere felis sed lacus');
insert into product_category (id, name, description) values (-372, 'Barr Boyat', 'in felis eu sapien cursus vestibulum');
insert into product_category (id, name, description) values (-373, 'Barbabas Sweedland', 'cubilia curae duis faucibus accumsan');
insert into product_category (id, name, description) values (-374, 'Carolin Hauger', 'habitasse platea dictumst morbi vestibulum velit id');
insert into product_category (id, name, description) values (-375, 'Rik Marke', 'turpis elementum ligula vehicula consequat morbi a ipsum integer a');
insert into product_category (id, name, description) values (-376, 'Caryl Salvati', 'dictumst etiam faucibus cursus urna ut');
insert into product_category (id, name, description) values (-377, 'Hobart Aitcheson', 'proin leo odio porttitor id');
insert into product_category (id, name, description) values (-378, 'Jake MacKaile', 'ut blandit non interdum in ante');
insert into product_category (id, name, description) values (-379, 'Rita Willishire', 'vel augue vestibulum rutrum rutrum neque aenean auctor');
insert into product_category (id, name, description) values (-380, 'Birk Crocker', 'tempus vivamus in felis eu sapien cursus vestibulum proin eu');
insert into product_category (id, name, description) values (-381, 'Danika Doubleday', 'dui maecenas tristique est et');
insert into product_category (id, name, description) values (-382, 'Austin Ranken', 'sed tincidunt eu felis fusce');
insert into product_category (id, name, description) values (-383, 'Isac Amerighi', 'est congue elementum in hac habitasse platea');
insert into product_category (id, name, description) values (-384, 'Katherina Taile', 'metus arcu adipiscing molestie hendrerit at vulputate');
insert into product_category (id, name, description) values (-385, 'Minne Boyford', 'luctus rutrum nulla tellus in sagittis dui vel nisl');
insert into product_category (id, name, description) values (-386, 'Matty Nuzzti', 'nisi eu orci mauris lacinia sapien quis libero nullam');
insert into product_category (id, name, description) values (-387, 'Rebeka Ewenson', 'leo odio porttitor id consequat in consequat ut nulla sed');
insert into product_category (id, name, description) values (-388, 'Lauritz McNiff', 'pellentesque quisque porta volutpat erat quisque erat eros viverra');
insert into product_category (id, name, description) values (-389, 'Auria Lanfere', 'vel enim sit amet nunc viverra dapibus nulla suscipit ligula');
insert into product_category (id, name, description) values (-390, 'Dewey Jurick', 'consequat lectus in est risus');
insert into product_category (id, name, description) values (-391, 'Stefan Crippes', 'sit amet diam in magna bibendum imperdiet');
insert into product_category (id, name, description) values (-392, 'Weber Sealy', 'commodo placerat praesent blandit nam nulla integer pede');
insert into product_category (id, name, description) values (-393, 'Hubert Maple', 'sapien non mi integer ac neque duis bibendum morbi non');
insert into product_category (id, name, description) values (-394, 'Violet Adenet', 'aliquam quis turpis eget elit sodales scelerisque mauris sit amet');
insert into product_category (id, name, description) values (-395, 'Ripley Blaise', 'nisi venenatis tristique fusce congue diam');
insert into product_category (id, name, description) values (-396, 'Benedikta Culkin', 'lacus at velit vivamus vel nulla eget eros elementum');
insert into product_category (id, name, description) values (-397, 'Harri Hutcheon', 'enim leo rhoncus sed vestibulum sit amet');
insert into product_category (id, name, description) values (-398, 'Lexie Longfield', 'duis bibendum felis sed interdum');
insert into product_category (id, name, description) values (-399, 'Phelia Ollarenshaw', 'mattis pulvinar nulla pede ullamcorper augue a suscipit nulla');
insert into product_category (id, name, description) values (-400, 'Marleen Silcox', 'nec nisi volutpat eleifend donec ut dolor morbi');
insert into product_category (id, name, description) values (-401, 'Lennie Albinson', 'ut erat curabitur gravida nisi at nibh in hac');
insert into product_category (id, name, description) values (-402, 'Rozanne Cardis', 'lorem ipsum dolor sit amet consectetuer adipiscing');
insert into product_category (id, name, description) values (-403, 'Farlay Jollie', 'primis in faucibus orci luctus');
insert into product_category (id, name, description) values (-404, 'Pauletta Sharpe', 'ultrices libero non mattis pulvinar');
insert into product_category (id, name, description) values (-405, 'Davida Hummerston', 'dictumst morbi vestibulum velit id pretium');
insert into product_category (id, name, description) values (-406, 'Juan Glede', 'lobortis ligula sit amet eleifend pede libero quis');
insert into product_category (id, name, description) values (-407, 'Eadith Hartzenberg', 'convallis tortor risus dapibus augue vel accumsan tellus');
insert into product_category (id, name, description) values (-408, 'Karoly Lecount', 'varius integer ac leo pellentesque ultrices mattis odio donec vitae');
insert into product_category (id, name, description) values (-409, 'Augustin Coggan', 'eu massa donec dapibus duis at velit');
insert into product_category (id, name, description) values (-410, 'Jeffie Rubanenko', 'donec odio justo sollicitudin ut suscipit');
insert into product_category (id, name, description) values (-411, 'Josee Stuchberry', 'duis aliquam convallis nunc proin at turpis a pede');
insert into product_category (id, name, description) values (-412, 'Ax Biaggioli', 'consequat nulla nisl nunc nisl duis bibendum felis sed interdum');
insert into product_category (id, name, description) values (-413, 'Christalle Manville', 'fusce congue diam id ornare imperdiet sapien urna');
insert into product_category (id, name, description) values (-414, 'Evvie Beale', 'lacus purus aliquet at feugiat non pretium');
insert into product_category (id, name, description) values (-415, 'Fredi Joinson', 'nibh in hac habitasse platea dictumst aliquam');
insert into product_category (id, name, description) values (-416, 'Kirsti Mechem', 'mauris vulputate elementum nullam varius');
insert into product_category (id, name, description) values (-417, 'Louella Crottagh', 'amet erat nulla tempus vivamus');
insert into product_category (id, name, description) values (-418, 'Thibaut Borton', 'dapibus nulla suscipit ligula in lacus curabitur');
insert into product_category (id, name, description) values (-419, 'Kare Angerstein', 'nisi volutpat eleifend donec ut dolor morbi vel');
insert into product_category (id, name, description) values (-420, 'Norene Loxdale', 'tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida');
insert into product_category (id, name, description) values (-421, 'Donny Mitkin', 'cras in purus eu magna vulputate luctus cum sociis natoque');
insert into product_category (id, name, description) values (-422, 'Mahalia Malcher', 'suspendisse potenti nullam porttitor lacus');
insert into product_category (id, name, description) values (-423, 'Aridatha Barter', 'pede venenatis non sodales sed');
insert into product_category (id, name, description) values (-424, 'Vidovic McManamon', 'risus auctor sed tristique in tempus');
insert into product_category (id, name, description) values (-425, 'Ekaterina Gerdes', 'imperdiet et commodo vulputate justo in blandit');
insert into product_category (id, name, description) values (-426, 'Norah Abriani', 'vel sem sed sagittis nam congue');
insert into product_category (id, name, description) values (-427, 'Hobart Stitle', 'luctus et ultrices posuere cubilia curae donec');
insert into product_category (id, name, description) values (-428, 'Siffre Syres', 'donec odio justo sollicitudin ut suscipit a feugiat et');
insert into product_category (id, name, description) values (-429, 'Gardy Ellor', 'elit proin risus praesent lectus vestibulum');
insert into product_category (id, name, description) values (-430, 'Tony Canty', 'libero nam dui proin leo odio');
insert into product_category (id, name, description) values (-431, 'Goran MacCulloch', 'pretium iaculis diam erat fermentum justo nec');
insert into product_category (id, name, description) values (-432, 'Earvin Byforth', 'curae mauris viverra diam vitae quam suspendisse');
insert into product_category (id, name, description) values (-433, 'Orren Trenholme', 'consequat metus sapien ut nunc vestibulum');
insert into product_category (id, name, description) values (-434, 'Gael Lindblad', 'erat vestibulum sed magna at nunc commodo placerat');
insert into product_category (id, name, description) values (-435, 'Rene Surtees', 'luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur');
insert into product_category (id, name, description) values (-436, 'Eden Moorhead', 'curabitur convallis duis consequat dui nec');
insert into product_category (id, name, description) values (-437, 'Townsend MacVean', 'consectetuer adipiscing elit proin interdum mauris non');
insert into product_category (id, name, description) values (-438, 'Lucy Steddall', 'semper rutrum nulla nunc purus phasellus');
insert into product_category (id, name, description) values (-439, 'Katlin Cope', 'nulla nunc purus phasellus in felis');
insert into product_category (id, name, description) values (-440, 'Alane Shurmer', 'nulla suscipit ligula in lacus curabitur at ipsum ac');
insert into product_category (id, name, description) values (-441, 'Beth Lethem', 'platea dictumst etiam faucibus cursus urna ut tellus nulla ut');
insert into product_category (id, name, description) values (-442, 'Pauly Cluff', 'nec nisi volutpat eleifend donec ut');
insert into product_category (id, name, description) values (-443, 'Demetris Lattimer', 'id consequat in consequat ut');
insert into product_category (id, name, description) values (-444, 'Farrel Clynman', 'pharetra magna vestibulum aliquet ultrices');
insert into product_category (id, name, description) values (-445, 'Augie Tebbit', 'ut massa volutpat convallis morbi odio');
insert into product_category (id, name, description) values (-446, 'Rupert Klagge', 'in hac habitasse platea dictumst maecenas ut massa');
insert into product_category (id, name, description) values (-447, 'Charleen Ashcroft', 'amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque');
insert into product_category (id, name, description) values (-448, 'Adella Lowen', 'amet sapien dignissim vestibulum vestibulum ante ipsum primis');
insert into product_category (id, name, description) values (-449, 'Jed L''oiseau', 'faucibus orci luctus et ultrices');
insert into product_category (id, name, description) values (-450, 'Lanette Carwithan', 'felis sed lacus morbi sem mauris laoreet ut rhoncus');
insert into product_category (id, name, description) values (-451, 'Danna Twells', 'pellentesque ultrices phasellus id sapien in sapien iaculis');
insert into product_category (id, name, description) values (-452, 'Martita Cescotti', 'sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit');
insert into product_category (id, name, description) values (-453, 'Andie Epelett', 'sapien cursus vestibulum proin eu mi nulla ac');
insert into product_category (id, name, description) values (-454, 'Mitchael Berthelmot', 'est phasellus sit amet erat');
insert into product_category (id, name, description) values (-455, 'Zea Stivey', 'iaculis justo in hac habitasse platea dictumst etiam faucibus');
insert into product_category (id, name, description) values (-456, 'Sabrina Breissan', 'tempus sit amet sem fusce consequat');
insert into product_category (id, name, description) values (-457, 'Charin Keemer', 'sit amet diam in magna');
insert into product_category (id, name, description) values (-458, 'Julee Barsby', 'semper rutrum nulla nunc purus');
insert into product_category (id, name, description) values (-459, 'Sukey Warbys', 'diam id ornare imperdiet sapien urna pretium nisl');
insert into product_category (id, name, description) values (-460, 'Yankee Lewnden', 'faucibus orci luctus et ultrices posuere cubilia curae');
insert into product_category (id, name, description) values (-461, 'Edgar Toxell', 'ac leo pellentesque ultrices mattis');
insert into product_category (id, name, description) values (-462, 'Jennica Manley', 'feugiat et eros vestibulum ac est lacinia nisi venenatis');
insert into product_category (id, name, description) values (-463, 'Susan Leupold', 'porta volutpat erat quisque erat eros');
insert into product_category (id, name, description) values (-464, 'Glori Andresen', 'donec pharetra magna vestibulum aliquet ultrices erat');
insert into product_category (id, name, description) values (-465, 'Emalee Hullyer', 'imperdiet nullam orci pede venenatis non sodales sed tincidunt eu');
insert into product_category (id, name, description) values (-466, 'Nisse Wackley', 'amet consectetuer adipiscing elit proin risus praesent');
insert into product_category (id, name, description) values (-467, 'Kimble Rihosek', 'at velit eu est congue');
insert into product_category (id, name, description) values (-468, 'Marylee Osborn', 'duis bibendum felis sed interdum venenatis turpis');
insert into product_category (id, name, description) values (-469, 'Dina Brundall', 'lacinia eget tincidunt eget tempus vel');
insert into product_category (id, name, description) values (-470, 'Hamlin Blythe', 'sit amet eros suspendisse accumsan tortor quis');
insert into product_category (id, name, description) values (-471, 'Hedda Kindley', 'posuere metus vitae ipsum aliquam');
insert into product_category (id, name, description) values (-472, 'Boonie Steanson', 'convallis nunc proin at turpis a pede posuere');
insert into product_category (id, name, description) values (-473, 'Urbanus Brumfitt', 'ornare consequat lectus in est risus auctor');
insert into product_category (id, name, description) values (-474, 'Eden Railton', 'consequat nulla nisl nunc nisl duis bibendum felis sed');
insert into product_category (id, name, description) values (-475, 'Illa Mustarde', 'proin risus praesent lectus vestibulum quam');
insert into product_category (id, name, description) values (-476, 'Ambrose Padefield', 'sapien dignissim vestibulum vestibulum ante ipsum');
insert into product_category (id, name, description) values (-477, 'Cris Turbayne', 'nonummy maecenas tincidunt lacus at velit vivamus vel nulla');
insert into product_category (id, name, description) values (-478, 'Aharon Duffrie', 'aliquam non mauris morbi non lectus');
insert into product_category (id, name, description) values (-479, 'Armand Rymer', 'sapien cum sociis natoque penatibus');
insert into product_category (id, name, description) values (-480, 'Evelina Legan', 'lacus morbi quis tortor id nulla ultrices aliquet');
insert into product_category (id, name, description) values (-481, 'Dagmar Larderot', 'in hac habitasse platea dictumst maecenas ut massa quis augue');
insert into product_category (id, name, description) values (-482, 'Vi Skain', 'erat volutpat in congue etiam justo');
insert into product_category (id, name, description) values (-483, 'Ruthy Algate', 'sapien varius ut blandit non interdum in ante vestibulum');
insert into product_category (id, name, description) values (-484, 'Margaretha Muccino', 'nec sem duis aliquam convallis nunc proin at turpis a');
insert into product_category (id, name, description) values (-485, 'Heddi Garry', 'at vulputate vitae nisl aenean lectus pellentesque');
insert into product_category (id, name, description) values (-486, 'Vittoria Buscher', 'at feugiat non pretium quis');
insert into product_category (id, name, description) values (-487, 'Jean Yurov', 'blandit lacinia erat vestibulum sed magna');
insert into product_category (id, name, description) values (-488, 'Ronald Santacrole', 'risus dapibus augue vel accumsan tellus nisi eu');
insert into product_category (id, name, description) values (-489, 'Brewer Giaomozzo', 'suspendisse potenti cras in purus');
insert into product_category (id, name, description) values (-490, 'Rubie Iapico', 'justo aliquam quis turpis eget elit sodales');
insert into product_category (id, name, description) values (-491, 'Thor Neary', 'sit amet cursus id turpis integer aliquet');
insert into product_category (id, name, description) values (-492, 'Casie Loache', 'amet erat nulla tempus vivamus in felis');
insert into product_category (id, name, description) values (-493, 'Lianne Brise', 'libero quis orci nullam molestie nibh in lectus');
insert into product_category (id, name, description) values (-494, 'Louie Worlidge', 'nulla quisque arcu libero rutrum ac lobortis vel');
insert into product_category (id, name, description) values (-495, 'Farlee Gemeau', 'in tempor turpis nec euismod scelerisque quam');
insert into product_category (id, name, description) values (-496, 'Crissy Kennedy', 'bibendum imperdiet nullam orci pede');
insert into product_category (id, name, description) values (-497, 'Leanor Linklater', 'donec diam neque vestibulum eget vulputate');
insert into product_category (id, name, description) values (-498, 'Jillene Wilderspoon', 'placerat ante nulla justo aliquam quis');
insert into product_category (id, name, description) values (-499, 'Cathryn Grishanin', 'felis ut at dolor quis odio consequat');
insert into product_category (id, name, description) values (-500, 'Barron McCrae', 'accumsan felis ut at dolor quis odio');
