insert into product_sub_category (id, name, description, product_category_id) values (-1, 'Edward Casson', 'bibendum felis sed interdum venenatis turpis enim blandit mi in', -242);
insert into product_sub_category (id, name, description, product_category_id) values (-2, 'Truda Alliker', 'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus', -196);
insert into product_sub_category (id, name, description, product_category_id) values (-3, 'Annabela Moulson', 'at vulputate vitae nisl aenean lectus pellentesque', -218);
insert into product_sub_category (id, name, description, product_category_id) values (-4, 'Jacob Bernardino', 'dui vel sem sed sagittis nam congue risus semper porta', -182);
insert into product_sub_category (id, name, description, product_category_id) values (-5, 'Verine Pendlebery', 'ac est lacinia nisi venenatis', -447);
insert into product_sub_category (id, name, description, product_category_id) values (-6, 'Farlie Cullabine', 'duis aliquam convallis nunc proin at turpis', -128);
insert into product_sub_category (id, name, description, product_category_id) values (-7, 'Dix Brugh', 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor id', -334);
insert into product_sub_category (id, name, description, product_category_id) values (-8, 'Izak Critch', 'in lacus curabitur at ipsum ac', -51);
insert into product_sub_category (id, name, description, product_category_id) values (-9, 'Onfre Ricardon', 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent', -123);
insert into product_sub_category (id, name, description, product_category_id) values (-10, 'Marita Bolzmann', 'hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer', -361);
insert into product_sub_category (id, name, description, product_category_id) values (-11, 'Hyacinthe Novelli', 'consequat in consequat ut nulla sed accumsan felis ut at', -2);
insert into product_sub_category (id, name, description, product_category_id) values (-12, 'Emelita Batcock', 'ultrices enim lorem ipsum dolor sit amet consectetuer', -422);
insert into product_sub_category (id, name, description, product_category_id) values (-13, 'Cicily Cyseley', 'ac est lacinia nisi venenatis tristique fusce', -113);
insert into product_sub_category (id, name, description, product_category_id) values (-14, 'Samson Gwilliams', 'nulla sed vel enim sit', -314);
insert into product_sub_category (id, name, description, product_category_id) values (-15, 'Hermina Jenton', 'faucibus cursus urna ut tellus nulla ut erat', -156);
insert into product_sub_category (id, name, description, product_category_id) values (-16, 'Silvester Stockey', 'consectetuer adipiscing elit proin interdum mauris non', -105);
insert into product_sub_category (id, name, description, product_category_id) values (-17, 'Daloris McMurrugh', 'natoque penatibus et magnis dis', -449);
insert into product_sub_category (id, name, description, product_category_id) values (-18, 'Agace Dransfield', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit', -404);
insert into product_sub_category (id, name, description, product_category_id) values (-19, 'Camey Matushevitz', 'id nisl venenatis lacinia aenean sit amet justo', -287);
insert into product_sub_category (id, name, description, product_category_id) values (-20, 'Nickolai Wenden', 'at velit eu est congue elementum in hac habitasse platea', -393);
insert into product_sub_category (id, name, description, product_category_id) values (-21, 'Lamont Tidbold', 'pede malesuada in imperdiet et commodo vulputate justo', -367);
insert into product_sub_category (id, name, description, product_category_id) values (-22, 'Elaina Portinari', 'nec condimentum neque sapien placerat ante nulla justo aliquam quis', -265);
insert into product_sub_category (id, name, description, product_category_id) values (-23, 'Jayme Braffington', 'nisi at nibh in hac habitasse', -417);
insert into product_sub_category (id, name, description, product_category_id) values (-24, 'Evangelin Filasov', 'eu nibh quisque id justo sit amet sapien', -98);
insert into product_sub_category (id, name, description, product_category_id) values (-25, 'Laurie Milnthorpe', 'amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur', -84);
insert into product_sub_category (id, name, description, product_category_id) values (-26, 'Dulcea Skupinski', 'elementum in hac habitasse platea', -253);
insert into product_sub_category (id, name, description, product_category_id) values (-27, 'Claudetta Jacobbe', 'id ornare imperdiet sapien urna pretium nisl ut', -365);
insert into product_sub_category (id, name, description, product_category_id) values (-28, 'Evangeline Aaron', 'ultrices phasellus id sapien in', -376);
insert into product_sub_category (id, name, description, product_category_id) values (-29, 'Dillon Craker', 'vulputate ut ultrices vel augue vestibulum ante ipsum primis in', -5);
insert into product_sub_category (id, name, description, product_category_id) values (-30, 'Laetitia Ebbitt', 'enim lorem ipsum dolor sit amet', -482);
insert into product_sub_category (id, name, description, product_category_id) values (-31, 'Lion Pickance', 'justo maecenas rhoncus aliquam lacus', -73);
insert into product_sub_category (id, name, description, product_category_id) values (-32, 'Corly Deal', 'proin leo odio porttitor id', -18);
insert into product_sub_category (id, name, description, product_category_id) values (-33, 'Jarad Clacson', 'nunc nisl duis bibendum felis sed interdum venenatis turpis', -193);
insert into product_sub_category (id, name, description, product_category_id) values (-34, 'Marty Rapelli', 'tortor risus dapibus augue vel accumsan tellus', -99);
insert into product_sub_category (id, name, description, product_category_id) values (-35, 'Kellia Dyte', 'sagittis dui vel nisl duis ac', -104);
insert into product_sub_category (id, name, description, product_category_id) values (-36, 'Tasha Kyme', 'sit amet diam in magna bibendum imperdiet nullam', -169);
insert into product_sub_category (id, name, description, product_category_id) values (-37, 'Dickie Kunrad', 'integer non velit donec diam neque vestibulum', -72);
insert into product_sub_category (id, name, description, product_category_id) values (-38, 'Christophe Vickarman', 'duis faucibus accumsan odio curabitur convallis duis', -494);
insert into product_sub_category (id, name, description, product_category_id) values (-39, 'Madel Lammers', 'dictumst etiam faucibus cursus urna', -363);
insert into product_sub_category (id, name, description, product_category_id) values (-40, 'Cody Annon', 'in hac habitasse platea dictumst etiam faucibus', -163);
insert into product_sub_category (id, name, description, product_category_id) values (-41, 'Emelen Bathoe', 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', -474);
insert into product_sub_category (id, name, description, product_category_id) values (-42, 'Hadleigh Vautier', 'adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque', -482);
insert into product_sub_category (id, name, description, product_category_id) values (-43, 'Giorgia Mignot', 'neque sapien placerat ante nulla justo aliquam quis', -12);
insert into product_sub_category (id, name, description, product_category_id) values (-44, 'Kellina Menere', 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio', -115);
insert into product_sub_category (id, name, description, product_category_id) values (-45, 'Isac Dinzey', 'luctus tincidunt nulla mollis molestie lorem quisque ut erat', -242);
insert into product_sub_category (id, name, description, product_category_id) values (-46, 'Kelby Bennis', 'suspendisse ornare consequat lectus in est', -254);
insert into product_sub_category (id, name, description, product_category_id) values (-47, 'Sondra Hovey', 'ut dolor morbi vel lectus in quam fringilla rhoncus', -173);
insert into product_sub_category (id, name, description, product_category_id) values (-48, 'Laurie Edmead', 'dolor quis odio consequat varius', -420);
insert into product_sub_category (id, name, description, product_category_id) values (-49, 'Leena Harrhy', 'turpis donec posuere metus vitae ipsum', -122);
insert into product_sub_category (id, name, description, product_category_id) values (-50, 'Annalee Pollock', 'ligula suspendisse ornare consequat lectus in', -438);
insert into product_sub_category (id, name, description, product_category_id) values (-51, 'Konstantine Snooks', 'iaculis justo in hac habitasse platea dictumst', -207);
insert into product_sub_category (id, name, description, product_category_id) values (-52, 'Shanda Mendel', 'donec vitae nisi nam ultrices libero', -353);
insert into product_sub_category (id, name, description, product_category_id) values (-53, 'Dale D''Antoni', 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam', -45);
insert into product_sub_category (id, name, description, product_category_id) values (-54, 'Sancho Plitz', 'faucibus orci luctus et ultrices posuere cubilia curae duis faucibus', -174);
insert into product_sub_category (id, name, description, product_category_id) values (-55, 'Gregor Murrthum', 'at velit vivamus vel nulla eget eros elementum pellentesque', -367);
insert into product_sub_category (id, name, description, product_category_id) values (-56, 'Marcus Ioan', 'vel augue vestibulum ante ipsum', -105);
insert into product_sub_category (id, name, description, product_category_id) values (-57, 'Boyce Greyes', 'molestie hendrerit at vulputate vitae nisl aenean', -331);
insert into product_sub_category (id, name, description, product_category_id) values (-58, 'Douglas Isaksson', 'nullam varius nulla facilisi cras non velit nec', -24);
insert into product_sub_category (id, name, description, product_category_id) values (-59, 'Claudia Nutman', 'id lobortis convallis tortor risus dapibus augue', -478);
insert into product_sub_category (id, name, description, product_category_id) values (-60, 'Camille Dict', 'suspendisse potenti nullam porttitor lacus at turpis donec posuere', -398);
insert into product_sub_category (id, name, description, product_category_id) values (-61, 'Ramsay Trudgian', 'pede libero quis orci nullam molestie nibh in', -478);
insert into product_sub_category (id, name, description, product_category_id) values (-62, 'Ashton Scraggs', 'pede libero quis orci nullam molestie nibh in lectus', -86);
insert into product_sub_category (id, name, description, product_category_id) values (-63, 'Pippa Gath', 'morbi quis tortor id nulla ultrices', -373);
insert into product_sub_category (id, name, description, product_category_id) values (-64, 'Roderick Bewshea', 'amet erat nulla tempus vivamus in', -40);
insert into product_sub_category (id, name, description, product_category_id) values (-65, 'Patrizio Lineen', 'enim blandit mi in porttitor pede justo eu massa donec', -452);
insert into product_sub_category (id, name, description, product_category_id) values (-66, 'Angie Worsall', 'sapien ut nunc vestibulum ante ipsum primis in faucibus orci', -182);
insert into product_sub_category (id, name, description, product_category_id) values (-67, 'Elnar Orringe', 'ante ipsum primis in faucibus orci luctus et ultrices', -359);
insert into product_sub_category (id, name, description, product_category_id) values (-68, 'Hettie Rosenblum', 'dignissim vestibulum vestibulum ante ipsum primis', -333);
insert into product_sub_category (id, name, description, product_category_id) values (-69, 'Brear Woolsey', 'erat curabitur gravida nisi at nibh in hac habitasse', -469);
insert into product_sub_category (id, name, description, product_category_id) values (-70, 'Inessa Ommundsen', 'in hac habitasse platea dictumst morbi vestibulum velit id pretium', -253);
insert into product_sub_category (id, name, description, product_category_id) values (-71, 'Vitoria Brigshaw', 'magna vulputate luctus cum sociis natoque penatibus et', -431);
insert into product_sub_category (id, name, description, product_category_id) values (-72, 'Tiler Brunel', 'justo aliquam quis turpis eget elit sodales scelerisque mauris', -202);
insert into product_sub_category (id, name, description, product_category_id) values (-73, 'Evy Erdis', 'libero rutrum ac lobortis vel dapibus at', -4);
insert into product_sub_category (id, name, description, product_category_id) values (-74, 'Neil Tinto', 'dis parturient montes nascetur ridiculus mus etiam vel augue', -184);
insert into product_sub_category (id, name, description, product_category_id) values (-75, 'Cristabel Hulatt', 'nulla neque libero convallis eget eleifend', -496);
insert into product_sub_category (id, name, description, product_category_id) values (-76, 'Hal Castana', 'facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt', -197);
insert into product_sub_category (id, name, description, product_category_id) values (-77, 'Dar Bumford', 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non', -134);
insert into product_sub_category (id, name, description, product_category_id) values (-78, 'Gaby Ascough', 'turpis a pede posuere nonummy integer', -409);
insert into product_sub_category (id, name, description, product_category_id) values (-79, 'Jermain McGillacoell', 'lorem integer tincidunt ante vel ipsum', -423);
insert into product_sub_category (id, name, description, product_category_id) values (-80, 'Marcy Lautie', 'orci mauris lacinia sapien quis libero nullam sit', -247);
insert into product_sub_category (id, name, description, product_category_id) values (-81, 'Ginnie Cavendish', 'porttitor id consequat in consequat ut nulla sed accumsan felis', -278);
insert into product_sub_category (id, name, description, product_category_id) values (-82, 'Cazzie O''Doohaine', 'eu mi nulla ac enim in tempor', -169);
insert into product_sub_category (id, name, description, product_category_id) values (-83, 'Chucho Verrechia', 'aenean lectus pellentesque eget nunc donec quis', -226);
insert into product_sub_category (id, name, description, product_category_id) values (-84, 'Oliviero Seagrave', 'ullamcorper augue a suscipit nulla elit ac nulla', -249);
insert into product_sub_category (id, name, description, product_category_id) values (-85, 'Elaine Coxall', 'posuere cubilia curae mauris viverra diam vitae quam suspendisse', -218);
insert into product_sub_category (id, name, description, product_category_id) values (-86, 'Libbey Readitt', 'sit amet sem fusce consequat nulla', -90);
insert into product_sub_category (id, name, description, product_category_id) values (-87, 'Sawyer Abberley', 'lobortis vel dapibus at diam', -94);
insert into product_sub_category (id, name, description, product_category_id) values (-88, 'Nesta Liggett', 'lorem quisque ut erat curabitur gravida', -408);
insert into product_sub_category (id, name, description, product_category_id) values (-89, 'Malachi Matokhnin', 'libero rutrum ac lobortis vel dapibus at', -378);
insert into product_sub_category (id, name, description, product_category_id) values (-90, 'Lamont Dutteridge', 'hac habitasse platea dictumst morbi vestibulum velit', -70);
insert into product_sub_category (id, name, description, product_category_id) values (-91, 'Ange Joutapavicius', 'turpis adipiscing lorem vitae mattis nibh ligula', -211);
insert into product_sub_category (id, name, description, product_category_id) values (-92, 'Susan Robe', 'dui maecenas tristique est et', -57);
insert into product_sub_category (id, name, description, product_category_id) values (-93, 'Roman Cinavas', 'sit amet sem fusce consequat nulla nisl', -239);
insert into product_sub_category (id, name, description, product_category_id) values (-94, 'Sterling Thiem', 'duis mattis egestas metus aenean fermentum', -355);
insert into product_sub_category (id, name, description, product_category_id) values (-95, 'Lil Fransemai', 'mi nulla ac enim in tempor', -151);
insert into product_sub_category (id, name, description, product_category_id) values (-96, 'Marthena Staterfield', 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis', -427);
insert into product_sub_category (id, name, description, product_category_id) values (-97, 'Reube Glazzard', 'in consequat ut nulla sed', -142);
insert into product_sub_category (id, name, description, product_category_id) values (-98, 'Mickey Petrillo', 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam', -190);
insert into product_sub_category (id, name, description, product_category_id) values (-99, 'Giralda McIlhatton', 'vitae nisl aenean lectus pellentesque', -48);
insert into product_sub_category (id, name, description, product_category_id) values (-100, 'Sergeant De Simoni', 'et eros vestibulum ac est lacinia', -315);
insert into product_sub_category (id, name, description, product_category_id) values (-101, 'Alaine Anyon', 'lobortis vel dapibus at diam nam', -78);
insert into product_sub_category (id, name, description, product_category_id) values (-102, 'Cecilio Lacknor', 'porttitor lacus at turpis donec posuere metus vitae ipsum', -313);
insert into product_sub_category (id, name, description, product_category_id) values (-103, 'Perl Bowmaker', 'in faucibus orci luctus et ultrices posuere cubilia curae duis', -128);
insert into product_sub_category (id, name, description, product_category_id) values (-104, 'Ferrell Thorndale', 'nulla suscipit ligula in lacus curabitur', -61);
insert into product_sub_category (id, name, description, product_category_id) values (-105, 'Faustina Voelker', 'dui proin leo odio porttitor id consequat in', -416);
insert into product_sub_category (id, name, description, product_category_id) values (-106, 'Emory Ades', 'platea dictumst etiam faucibus cursus urna ut tellus nulla', -266);
insert into product_sub_category (id, name, description, product_category_id) values (-107, 'Abraham Sitch', 'ullamcorper augue a suscipit nulla elit ac nulla', -264);
insert into product_sub_category (id, name, description, product_category_id) values (-108, 'Gerta Stamper', 'hac habitasse platea dictumst morbi vestibulum velit', -34);
insert into product_sub_category (id, name, description, product_category_id) values (-109, 'Tania Petticrow', 'sed augue aliquam erat volutpat in congue etiam justo etiam', -118);
insert into product_sub_category (id, name, description, product_category_id) values (-110, 'Earvin Featley', 'lobortis ligula sit amet eleifend pede', -500);
insert into product_sub_category (id, name, description, product_category_id) values (-111, 'Jeri Nusche', 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet', -353);
insert into product_sub_category (id, name, description, product_category_id) values (-112, 'Rachele Cripin', 'molestie nibh in lectus pellentesque at nulla', -209);
insert into product_sub_category (id, name, description, product_category_id) values (-113, 'Sally Ryal', 'non sodales sed tincidunt eu felis fusce posuere felis', -466);
insert into product_sub_category (id, name, description, product_category_id) values (-114, 'Kaia Ainscow', 'proin interdum mauris non ligula pellentesque', -342);
insert into product_sub_category (id, name, description, product_category_id) values (-115, 'Nixie Penrose', 'neque sapien placerat ante nulla justo aliquam', -165);
insert into product_sub_category (id, name, description, product_category_id) values (-116, 'Nadia Chalcot', 'lorem ipsum dolor sit amet', -492);
insert into product_sub_category (id, name, description, product_category_id) values (-117, 'Monica Straughan', 'erat fermentum justo nec condimentum neque sapien', -165);
insert into product_sub_category (id, name, description, product_category_id) values (-118, 'Onfroi Spring', 'quam suspendisse potenti nullam porttitor lacus', -383);
insert into product_sub_category (id, name, description, product_category_id) values (-119, 'Sammy Davet', 'purus phasellus in felis donec semper sapien a libero', -447);
insert into product_sub_category (id, name, description, product_category_id) values (-120, 'Thea Reinmar', 'dictumst etiam faucibus cursus urna ut', -397);
insert into product_sub_category (id, name, description, product_category_id) values (-121, 'Alayne Ianetti', 'aliquam non mauris morbi non lectus aliquam sit', -292);
insert into product_sub_category (id, name, description, product_category_id) values (-122, 'Roxanne Bortolotti', 'pede ullamcorper augue a suscipit nulla elit', -317);
insert into product_sub_category (id, name, description, product_category_id) values (-123, 'Meggi Ivens', 'sed ante vivamus tortor duis mattis egestas metus', -461);
insert into product_sub_category (id, name, description, product_category_id) values (-124, 'Alejandra Van der Mark', 'ac consequat metus sapien ut nunc', -330);
insert into product_sub_category (id, name, description, product_category_id) values (-125, 'Joey Paniman', 'ultrices libero non mattis pulvinar nulla pede ullamcorper augue', -425);
insert into product_sub_category (id, name, description, product_category_id) values (-126, 'Cullin Rapelli', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula', -201);
insert into product_sub_category (id, name, description, product_category_id) values (-127, 'Virge Borris', 'interdum mauris non ligula pellentesque ultrices phasellus id', -51);
insert into product_sub_category (id, name, description, product_category_id) values (-128, 'Flory Winterburn', 'etiam justo etiam pretium iaculis justo in hac habitasse', -498);
insert into product_sub_category (id, name, description, product_category_id) values (-129, 'Lorin Duckinfield', 'porttitor pede justo eu massa donec dapibus duis', -97);
insert into product_sub_category (id, name, description, product_category_id) values (-130, 'Janeczka Maile', 'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel', -169);
insert into product_sub_category (id, name, description, product_category_id) values (-131, 'Boniface Woolpert', 'dui proin leo odio porttitor id consequat', -273);
insert into product_sub_category (id, name, description, product_category_id) values (-132, 'Cirillo Kendall', 'iaculis congue vivamus metus arcu adipiscing molestie', -297);
insert into product_sub_category (id, name, description, product_category_id) values (-133, 'Raymond Weekley', 'morbi non quam nec dui luctus rutrum nulla tellus in', -442);
insert into product_sub_category (id, name, description, product_category_id) values (-134, 'Nannie Attree', 'semper sapien a libero nam dui proin leo', -72);
insert into product_sub_category (id, name, description, product_category_id) values (-135, 'Brady Tidbold', 'tristique fusce congue diam id ornare', -435);
insert into product_sub_category (id, name, description, product_category_id) values (-136, 'Terese Tack', 'ac lobortis vel dapibus at diam nam', -266);
insert into product_sub_category (id, name, description, product_category_id) values (-137, 'Northrup Punch', 'leo maecenas pulvinar lobortis est phasellus sit amet', -296);
insert into product_sub_category (id, name, description, product_category_id) values (-138, 'Tina Berka', 'praesent lectus vestibulum quam sapien', -225);
insert into product_sub_category (id, name, description, product_category_id) values (-139, 'Rici Leaming', 'ac lobortis vel dapibus at diam nam tristique tortor', -366);
insert into product_sub_category (id, name, description, product_category_id) values (-140, 'Keefe Muschette', 'nisi venenatis tristique fusce congue diam id ornare', -374);
insert into product_sub_category (id, name, description, product_category_id) values (-141, 'Maurits Easby', 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh', -335);
insert into product_sub_category (id, name, description, product_category_id) values (-142, 'Skyler McGonigal', 'eleifend pede libero quis orci nullam molestie', -188);
insert into product_sub_category (id, name, description, product_category_id) values (-143, 'Angelle Lunge', 'consectetuer eget rutrum at lorem integer', -48);
insert into product_sub_category (id, name, description, product_category_id) values (-144, 'Jasper Mulles', 'semper porta volutpat quam pede lobortis ligula', -341);
insert into product_sub_category (id, name, description, product_category_id) values (-145, 'Margaret Myhill', 'velit id pretium iaculis diam erat', -270);
insert into product_sub_category (id, name, description, product_category_id) values (-146, 'Alleen Augustine', 'nec dui luctus rutrum nulla tellus in sagittis dui vel', -59);
insert into product_sub_category (id, name, description, product_category_id) values (-147, 'Quintin Jansen', 'odio odio elementum eu interdum', -72);
insert into product_sub_category (id, name, description, product_category_id) values (-148, 'Maressa Varfolomeev', 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat', -132);
insert into product_sub_category (id, name, description, product_category_id) values (-149, 'Ahmed Clacson', 'quis augue luctus tincidunt nulla', -171);
insert into product_sub_category (id, name, description, product_category_id) values (-150, 'Sawyer Cotta', 'nec euismod scelerisque quam turpis adipiscing lorem vitae', -106);
insert into product_sub_category (id, name, description, product_category_id) values (-151, 'Rosemary Balkwill', 'id ligula suspendisse ornare consequat', -181);
insert into product_sub_category (id, name, description, product_category_id) values (-152, 'Theodor Walkling', 'tortor quis turpis sed ante', -82);
insert into product_sub_category (id, name, description, product_category_id) values (-153, 'Wenda Dykins', 'enim blandit mi in porttitor', -277);
insert into product_sub_category (id, name, description, product_category_id) values (-154, 'Wally Brewis', 'et magnis dis parturient montes', -409);
insert into product_sub_category (id, name, description, product_category_id) values (-155, 'Ernie Quodling', 'massa donec dapibus duis at velit', -498);
insert into product_sub_category (id, name, description, product_category_id) values (-156, 'Lorraine Magson', 'in imperdiet et commodo vulputate justo in blandit ultrices enim', -281);
insert into product_sub_category (id, name, description, product_category_id) values (-157, 'Candie Freckelton', 'augue a suscipit nulla elit ac nulla sed vel', -10);
insert into product_sub_category (id, name, description, product_category_id) values (-158, 'Lonnie Wilkisson', 'elementum eu interdum eu tincidunt in leo', -444);
insert into product_sub_category (id, name, description, product_category_id) values (-159, 'Tracie Sturdey', 'lacus at turpis donec posuere metus vitae ipsum aliquam', -364);
insert into product_sub_category (id, name, description, product_category_id) values (-160, 'Elianora Christley', 'ullamcorper augue a suscipit nulla elit ac nulla', -247);
insert into product_sub_category (id, name, description, product_category_id) values (-161, 'Rivi Instrell', 'nunc rhoncus dui vel sem', -250);
insert into product_sub_category (id, name, description, product_category_id) values (-162, 'Alano Dorracott', 'mauris enim leo rhoncus sed vestibulum sit amet', -397);
insert into product_sub_category (id, name, description, product_category_id) values (-163, 'Brand Turfes', 'ac enim in tempor turpis', -460);
insert into product_sub_category (id, name, description, product_category_id) values (-164, 'Annalee Matushevitz', 'dictumst aliquam augue quam sollicitudin vitae consectetuer eget', -301);
insert into product_sub_category (id, name, description, product_category_id) values (-165, 'Leonardo Childers', 'dolor sit amet consectetuer adipiscing elit', -247);
insert into product_sub_category (id, name, description, product_category_id) values (-166, 'Florrie Corringham', 'tellus nulla ut erat id mauris vulputate elementum nullam', -78);
insert into product_sub_category (id, name, description, product_category_id) values (-167, 'Laverna Dener', 'condimentum id luctus nec molestie sed justo pellentesque viverra', -238);
insert into product_sub_category (id, name, description, product_category_id) values (-168, 'Charmian Sheach', 'et ultrices posuere cubilia curae mauris viverra diam', -404);
insert into product_sub_category (id, name, description, product_category_id) values (-169, 'Katuscha De Winton', 'sed ante vivamus tortor duis', -220);
insert into product_sub_category (id, name, description, product_category_id) values (-170, 'Laurie Dulany', 'in consequat ut nulla sed', -133);
insert into product_sub_category (id, name, description, product_category_id) values (-171, 'Joseito Kippin', 'ac est lacinia nisi venenatis', -442);
insert into product_sub_category (id, name, description, product_category_id) values (-172, 'Francesca Cay', 'at turpis donec posuere metus', -372);
insert into product_sub_category (id, name, description, product_category_id) values (-173, 'Hector Lelievre', 'felis donec semper sapien a libero nam dui proin', -422);
insert into product_sub_category (id, name, description, product_category_id) values (-174, 'Arron Streets', 'mauris viverra diam vitae quam suspendisse', -75);
insert into product_sub_category (id, name, description, product_category_id) values (-175, 'Lydon Margach', 'sapien cum sociis natoque penatibus', -79);
insert into product_sub_category (id, name, description, product_category_id) values (-176, 'Bertie Koppen', 'aenean fermentum donec ut mauris eget massa tempor', -109);
insert into product_sub_category (id, name, description, product_category_id) values (-177, 'Marice Flecknoe', 'et commodo vulputate justo in blandit ultrices enim', -478);
insert into product_sub_category (id, name, description, product_category_id) values (-178, 'Gradeigh Tomlinson', 'cursus urna ut tellus nulla ut erat', -499);
insert into product_sub_category (id, name, description, product_category_id) values (-179, 'Carlene Cuttler', 'hendrerit at vulputate vitae nisl', -344);
insert into product_sub_category (id, name, description, product_category_id) values (-180, 'Corey Baudoux', 'ornare imperdiet sapien urna pretium nisl ut volutpat', -124);
insert into product_sub_category (id, name, description, product_category_id) values (-181, 'Scarlett Heckner', 'consectetuer eget rutrum at lorem integer tincidunt', -273);
insert into product_sub_category (id, name, description, product_category_id) values (-182, 'Gaby Grotty', 'adipiscing molestie hendrerit at vulputate vitae nisl', -241);
insert into product_sub_category (id, name, description, product_category_id) values (-183, 'Leoine Rumgay', 'sem praesent id massa id nisl', -424);
insert into product_sub_category (id, name, description, product_category_id) values (-184, 'Delcine Botting', 'volutpat eleifend donec ut dolor morbi vel lectus in quam', -8);
insert into product_sub_category (id, name, description, product_category_id) values (-185, 'Ev Springle', 'integer pede justo lacinia eget', -358);
insert into product_sub_category (id, name, description, product_category_id) values (-186, 'Susanna Sheerman', 'nisi volutpat eleifend donec ut dolor morbi', -306);
insert into product_sub_category (id, name, description, product_category_id) values (-187, 'Alonso Bearblock', 'donec quis orci eget orci vehicula condimentum curabitur in libero', -62);
insert into product_sub_category (id, name, description, product_category_id) values (-188, 'Janine Leaney', 'justo eu massa donec dapibus duis', -349);
insert into product_sub_category (id, name, description, product_category_id) values (-189, 'Bethany Corstan', 'curabitur in libero ut massa', -469);
insert into product_sub_category (id, name, description, product_category_id) values (-190, 'Obed Bolsteridge', 'praesent blandit lacinia erat vestibulum', -51);
insert into product_sub_category (id, name, description, product_category_id) values (-191, 'Riordan Eddow', 'mattis nibh ligula nec sem duis', -172);
insert into product_sub_category (id, name, description, product_category_id) values (-192, 'Jaquenetta Loynton', 'semper est quam pharetra magna ac consequat', -435);
insert into product_sub_category (id, name, description, product_category_id) values (-193, 'Verene Tomaszkiewicz', 'et ultrices posuere cubilia curae', -373);
insert into product_sub_category (id, name, description, product_category_id) values (-194, 'Bartholomeus Waby', 'amet turpis elementum ligula vehicula consequat morbi a ipsum', -470);
insert into product_sub_category (id, name, description, product_category_id) values (-195, 'Darice Beaconsall', 'nunc vestibulum ante ipsum primis', -127);
insert into product_sub_category (id, name, description, product_category_id) values (-196, 'Tiffie Bignell', 'ac diam cras pellentesque volutpat dui maecenas tristique est', -158);
insert into product_sub_category (id, name, description, product_category_id) values (-197, 'Clayton Idney', 'nulla elit ac nulla sed vel enim', -48);
insert into product_sub_category (id, name, description, product_category_id) values (-198, 'Shepard Drew', 'eu nibh quisque id justo sit amet sapien dignissim', -204);
insert into product_sub_category (id, name, description, product_category_id) values (-199, 'Fee Fruen', 'a suscipit nulla elit ac', -86);
insert into product_sub_category (id, name, description, product_category_id) values (-200, 'Easter Woodstock', 'ipsum dolor sit amet consectetuer adipiscing elit proin risus', -378);
insert into product_sub_category (id, name, description, product_category_id) values (-201, 'Emlyn Pawsey', 'posuere metus vitae ipsum aliquam non mauris morbi non lectus', -194);
insert into product_sub_category (id, name, description, product_category_id) values (-202, 'Emmalyn Scothron', 'non mi integer ac neque duis bibendum morbi non', -164);
insert into product_sub_category (id, name, description, product_category_id) values (-203, 'Donia Finci', 'non mauris morbi non lectus aliquam sit', -86);
insert into product_sub_category (id, name, description, product_category_id) values (-204, 'Josh Wolfindale', 'nisi volutpat eleifend donec ut dolor morbi', -32);
insert into product_sub_category (id, name, description, product_category_id) values (-205, 'Morganica Damato', 'turpis eget elit sodales scelerisque', -82);
insert into product_sub_category (id, name, description, product_category_id) values (-206, 'Leoine Rogger', 'ipsum primis in faucibus orci', -349);
insert into product_sub_category (id, name, description, product_category_id) values (-207, 'Carmina Matushevitz', 'ultrices vel augue vestibulum ante ipsum primis in', -187);
insert into product_sub_category (id, name, description, product_category_id) values (-208, 'Dominik Mableson', 'ornare imperdiet sapien urna pretium nisl ut volutpat', -423);
insert into product_sub_category (id, name, description, product_category_id) values (-209, 'Cherish Toke', 'arcu libero rutrum ac lobortis vel dapibus at diam', -116);
insert into product_sub_category (id, name, description, product_category_id) values (-210, 'Cati Duncan', 'morbi non lectus aliquam sit amet', -477);
insert into product_sub_category (id, name, description, product_category_id) values (-211, 'Brooke Lilleycrop', 'turpis a pede posuere nonummy integer', -445);
insert into product_sub_category (id, name, description, product_category_id) values (-212, 'Alon Gipps', 'odio donec vitae nisi nam ultrices', -62);
insert into product_sub_category (id, name, description, product_category_id) values (-213, 'Roy Dowda', 'luctus et ultrices posuere cubilia curae', -278);
insert into product_sub_category (id, name, description, product_category_id) values (-214, 'Karlyn Rubury', 'dolor vel est donec odio justo', -386);
insert into product_sub_category (id, name, description, product_category_id) values (-215, 'Lorine Padley', 'vivamus vel nulla eget eros elementum pellentesque quisque porta', -475);
insert into product_sub_category (id, name, description, product_category_id) values (-216, 'Emmye Hamsher', 'elit ac nulla sed vel enim sit amet', -290);
insert into product_sub_category (id, name, description, product_category_id) values (-217, 'Malvin Buxy', 'potenti in eleifend quam a odio in', -162);
insert into product_sub_category (id, name, description, product_category_id) values (-218, 'Ignaz Lethbridge', 'vitae mattis nibh ligula nec sem', -361);
insert into product_sub_category (id, name, description, product_category_id) values (-219, 'Ariana Dossantos', 'eu est congue elementum in hac habitasse platea dictumst morbi', -494);
insert into product_sub_category (id, name, description, product_category_id) values (-220, 'Granny Dyte', 'non mi integer ac neque duis', -232);
insert into product_sub_category (id, name, description, product_category_id) values (-221, 'Lynna Thorpe', 'felis eu sapien cursus vestibulum proin eu mi', -417);
insert into product_sub_category (id, name, description, product_category_id) values (-222, 'Maurita Kubczak', 'arcu libero rutrum ac lobortis vel dapibus at diam nam', -329);
insert into product_sub_category (id, name, description, product_category_id) values (-223, 'Adrianna Bysshe', 'maecenas rhoncus aliquam lacus morbi quis tortor id nulla', -496);
insert into product_sub_category (id, name, description, product_category_id) values (-224, 'Adaline Fairbrass', 'non mauris morbi non lectus aliquam', -41);
insert into product_sub_category (id, name, description, product_category_id) values (-225, 'Raquela Moggach', 'sapien arcu sed augue aliquam erat volutpat in congue', -49);
insert into product_sub_category (id, name, description, product_category_id) values (-226, 'Amabel Teesdale', 'vulputate elementum nullam varius nulla facilisi cras non velit nec', -413);
insert into product_sub_category (id, name, description, product_category_id) values (-227, 'Hayyim Benley', 'turpis integer aliquet massa id lobortis convallis tortor risus dapibus', -379);
insert into product_sub_category (id, name, description, product_category_id) values (-228, 'Feodora Olivetta', 'diam neque vestibulum eget vulputate ut ultrices vel augue', -384);
insert into product_sub_category (id, name, description, product_category_id) values (-229, 'Mariam Greenin', 'aliquam quis turpis eget elit sodales', -319);
insert into product_sub_category (id, name, description, product_category_id) values (-230, 'Trueman Flude', 'in felis eu sapien cursus vestibulum proin eu', -116);
insert into product_sub_category (id, name, description, product_category_id) values (-231, 'Griffie Monelle', 'sagittis nam congue risus semper', -311);
insert into product_sub_category (id, name, description, product_category_id) values (-232, 'Georgi Luparti', 'sit amet lobortis sapien sapien non mi', -364);
insert into product_sub_category (id, name, description, product_category_id) values (-233, 'Cassie Kopke', 'eros viverra eget congue eget semper rutrum nulla nunc', -223);
insert into product_sub_category (id, name, description, product_category_id) values (-234, 'Tiffi Tamburo', 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum', -78);
insert into product_sub_category (id, name, description, product_category_id) values (-235, 'Merl Le Strange', 'quis odio consequat varius integer ac', -446);
insert into product_sub_category (id, name, description, product_category_id) values (-236, 'Cynthia Caws', 'purus aliquet at feugiat non pretium quis lectus', -232);
insert into product_sub_category (id, name, description, product_category_id) values (-237, 'Ludovika Brave', 'luctus nec molestie sed justo pellentesque viverra pede ac diam', -152);
insert into product_sub_category (id, name, description, product_category_id) values (-238, 'Webb Gorman', 'justo maecenas rhoncus aliquam lacus morbi', -162);
insert into product_sub_category (id, name, description, product_category_id) values (-239, 'Willi Iannazzi', 'interdum mauris non ligula pellentesque ultrices', -481);
insert into product_sub_category (id, name, description, product_category_id) values (-240, 'Iosep Bettridge', 'luctus tincidunt nulla mollis molestie lorem quisque', -262);
insert into product_sub_category (id, name, description, product_category_id) values (-241, 'Atalanta Hauxby', 'vehicula consequat morbi a ipsum', -64);
insert into product_sub_category (id, name, description, product_category_id) values (-242, 'Victoria Gheraldi', 'vestibulum eget vulputate ut ultrices', -435);
insert into product_sub_category (id, name, description, product_category_id) values (-243, 'Lane Scotting', 'vel pede morbi porttitor lorem id ligula suspendisse', -391);
insert into product_sub_category (id, name, description, product_category_id) values (-244, 'Sansone Rennock', 'at vulputate vitae nisl aenean lectus pellentesque', -346);
insert into product_sub_category (id, name, description, product_category_id) values (-245, 'Honor Legh', 'donec quis orci eget orci vehicula condimentum curabitur in', -245);
insert into product_sub_category (id, name, description, product_category_id) values (-246, 'Keenan Tschierasche', 'libero nam dui proin leo odio porttitor id consequat in', -429);
insert into product_sub_category (id, name, description, product_category_id) values (-247, 'Phaedra Paintain', 'vestibulum sed magna at nunc commodo placerat praesent blandit nam', -127);
insert into product_sub_category (id, name, description, product_category_id) values (-248, 'Duncan Guppie', 'libero non mattis pulvinar nulla pede ullamcorper augue', -120);
insert into product_sub_category (id, name, description, product_category_id) values (-249, 'Camel Hurton', 'nec dui luctus rutrum nulla tellus in sagittis', -191);
insert into product_sub_category (id, name, description, product_category_id) values (-250, 'Joeann Flood', 'quis libero nullam sit amet', -304);
insert into product_sub_category (id, name, description, product_category_id) values (-251, 'Kris Barge', 'sed nisl nunc rhoncus dui vel sem sed sagittis', -256);
insert into product_sub_category (id, name, description, product_category_id) values (-252, 'Eileen Veighey', 'quisque erat eros viverra eget congue eget', -305);
insert into product_sub_category (id, name, description, product_category_id) values (-253, 'Alexandro Kniveton', 'platea dictumst maecenas ut massa quis augue', -8);
insert into product_sub_category (id, name, description, product_category_id) values (-254, 'Lemmy McCahey', 'pulvinar lobortis est phasellus sit amet erat', -78);
insert into product_sub_category (id, name, description, product_category_id) values (-255, 'Sammie Royce', 'eget massa tempor convallis nulla neque libero', -456);
insert into product_sub_category (id, name, description, product_category_id) values (-256, 'Denni McIlwreath', 'eleifend quam a odio in', -251);
insert into product_sub_category (id, name, description, product_category_id) values (-257, 'Ambur Farreil', 'fringilla rhoncus mauris enim leo rhoncus sed vestibulum', -32);
insert into product_sub_category (id, name, description, product_category_id) values (-258, 'Gabbey Jephcote', 'quam pharetra magna ac consequat', -107);
insert into product_sub_category (id, name, description, product_category_id) values (-259, 'Noni Froggatt', 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien', -429);
insert into product_sub_category (id, name, description, product_category_id) values (-260, 'Nicoli Pessolt', 'volutpat in congue etiam justo etiam pretium iaculis justo', -348);
insert into product_sub_category (id, name, description, product_category_id) values (-261, 'Zacharias Glamart', 'tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed', -49);
insert into product_sub_category (id, name, description, product_category_id) values (-262, 'Stanwood Pebworth', 'turpis integer aliquet massa id', -89);
insert into product_sub_category (id, name, description, product_category_id) values (-263, 'Haslett Bougourd', 'nisl nunc nisl duis bibendum', -54);
insert into product_sub_category (id, name, description, product_category_id) values (-264, 'Anetta Lough', 'phasellus id sapien in sapien iaculis congue vivamus metus', -348);
insert into product_sub_category (id, name, description, product_category_id) values (-265, 'Benjamin McMylor', 'justo in blandit ultrices enim lorem ipsum dolor sit amet', -347);
insert into product_sub_category (id, name, description, product_category_id) values (-266, 'Piotr Ballam', 'sem fusce consequat nulla nisl nunc', -180);
insert into product_sub_category (id, name, description, product_category_id) values (-267, 'Stepha Cham', 'quam suspendisse potenti nullam porttitor lacus at turpis', -182);
insert into product_sub_category (id, name, description, product_category_id) values (-268, 'Elwira Basnett', 'porttitor lorem id ligula suspendisse', -167);
insert into product_sub_category (id, name, description, product_category_id) values (-269, 'Johan Rablin', 'habitasse platea dictumst maecenas ut', -221);
insert into product_sub_category (id, name, description, product_category_id) values (-270, 'Koralle Giraldez', 'eu magna vulputate luctus cum sociis natoque penatibus et', -461);
insert into product_sub_category (id, name, description, product_category_id) values (-271, 'Clevie Gerant', 'interdum in ante vestibulum ante ipsum primis in faucibus orci', -110);
insert into product_sub_category (id, name, description, product_category_id) values (-272, 'Christean Cutsforth', 'mollis molestie lorem quisque ut', -138);
insert into product_sub_category (id, name, description, product_category_id) values (-273, 'Tommie Monkman', 'sapien cursus vestibulum proin eu mi nulla ac enim', -436);
insert into product_sub_category (id, name, description, product_category_id) values (-274, 'Tasia Loxston', 'rhoncus aliquam lacus morbi quis tortor id', -283);
insert into product_sub_category (id, name, description, product_category_id) values (-275, 'Rivalee Clowser', 'vestibulum velit id pretium iaculis diam erat fermentum justo nec', -7);
insert into product_sub_category (id, name, description, product_category_id) values (-276, 'Culver Blaske', 'interdum eu tincidunt in leo', -357);
insert into product_sub_category (id, name, description, product_category_id) values (-277, 'Thomas Sally', 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque', -39);
insert into product_sub_category (id, name, description, product_category_id) values (-278, 'Jane Fulkes', 'et ultrices posuere cubilia curae mauris', -62);
insert into product_sub_category (id, name, description, product_category_id) values (-279, 'Sheila Andrault', 'aliquet ultrices erat tortor sollicitudin', -206);
insert into product_sub_category (id, name, description, product_category_id) values (-280, 'Anabel Follen', 'ante nulla justo aliquam quis turpis eget', -290);
insert into product_sub_category (id, name, description, product_category_id) values (-281, 'Carmine Spalding', 'proin at turpis a pede posuere nonummy integer', -475);
insert into product_sub_category (id, name, description, product_category_id) values (-282, 'Cherida Scottesmoor', 'justo pellentesque viverra pede ac diam cras pellentesque volutpat', -42);
insert into product_sub_category (id, name, description, product_category_id) values (-283, 'Sydney Danihel', 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus', -287);
insert into product_sub_category (id, name, description, product_category_id) values (-284, 'Dallas Van der Hoeven', 'quam nec dui luctus rutrum nulla tellus in sagittis dui', -148);
insert into product_sub_category (id, name, description, product_category_id) values (-285, 'Holly-anne Hawsby', 'at nulla suspendisse potenti cras in', -148);
insert into product_sub_category (id, name, description, product_category_id) values (-286, 'Nessie Hubbucks', 'velit id pretium iaculis diam erat', -340);
insert into product_sub_category (id, name, description, product_category_id) values (-287, 'Michael Sylvaine', 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', -7);
insert into product_sub_category (id, name, description, product_category_id) values (-288, 'Maia Sagg', 'nulla suscipit ligula in lacus curabitur', -231);
insert into product_sub_category (id, name, description, product_category_id) values (-289, 'Alisander Murby', 'non mauris morbi non lectus', -483);
insert into product_sub_category (id, name, description, product_category_id) values (-290, 'Yance Gitthouse', 'elit proin risus praesent lectus', -139);
insert into product_sub_category (id, name, description, product_category_id) values (-291, 'Skip Igounet', 'urna ut tellus nulla ut erat id mauris', -175);
insert into product_sub_category (id, name, description, product_category_id) values (-292, 'Wainwright Weatherhill', 'suscipit nulla elit ac nulla sed', -427);
insert into product_sub_category (id, name, description, product_category_id) values (-293, 'Harland Martinetto', 'in porttitor pede justo eu massa', -470);
insert into product_sub_category (id, name, description, product_category_id) values (-294, 'Inessa Cooksley', 'mi pede malesuada in imperdiet et commodo vulputate', -346);
insert into product_sub_category (id, name, description, product_category_id) values (-295, 'Staffard Gaffey', 'sed sagittis nam congue risus semper porta', -399);
insert into product_sub_category (id, name, description, product_category_id) values (-296, 'Melinde Barts', 'congue diam id ornare imperdiet sapien urna pretium nisl ut', -333);
insert into product_sub_category (id, name, description, product_category_id) values (-297, 'Zedekiah Boorne', 'pede ullamcorper augue a suscipit nulla elit ac', -211);
insert into product_sub_category (id, name, description, product_category_id) values (-298, 'Trefor Calyton', 'ipsum dolor sit amet consectetuer adipiscing elit proin interdum', -401);
insert into product_sub_category (id, name, description, product_category_id) values (-299, 'Nikaniki Mathet', 'erat quisque erat eros viverra eget congue', -29);
insert into product_sub_category (id, name, description, product_category_id) values (-300, 'Zebulon McPhillimey', 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet', -416);
insert into product_sub_category (id, name, description, product_category_id) values (-301, 'Quill Smallcomb', 'tempor convallis nulla neque libero convallis eget eleifend', -497);
insert into product_sub_category (id, name, description, product_category_id) values (-302, 'Rakel Jans', 'convallis nulla neque libero convallis eget eleifend luctus', -32);
insert into product_sub_category (id, name, description, product_category_id) values (-303, 'Etheline Alltimes', 'integer aliquet massa id lobortis', -189);
insert into product_sub_category (id, name, description, product_category_id) values (-304, 'Neils Tuxill', 'leo pellentesque ultrices mattis odio donec vitae nisi nam', -258);
insert into product_sub_category (id, name, description, product_category_id) values (-305, 'Theresa Goodwill', 'leo rhoncus sed vestibulum sit amet cursus id turpis integer', -415);
insert into product_sub_category (id, name, description, product_category_id) values (-306, 'Silvie Greeves', 'non lectus aliquam sit amet diam in magna bibendum', -157);
insert into product_sub_category (id, name, description, product_category_id) values (-307, 'Mitzi Baudou', 'tortor duis mattis egestas metus', -436);
insert into product_sub_category (id, name, description, product_category_id) values (-308, 'Gideon Strank', 'congue elementum in hac habitasse platea dictumst morbi', -268);
insert into product_sub_category (id, name, description, product_category_id) values (-309, 'Shelley Goney', 'ipsum primis in faucibus orci luctus et ultrices', -124);
insert into product_sub_category (id, name, description, product_category_id) values (-310, 'Thebault Grunnell', 'morbi non lectus aliquam sit amet diam in magna bibendum', -14);
insert into product_sub_category (id, name, description, product_category_id) values (-311, 'Hakeem Ishchenko', 'pretium iaculis diam erat fermentum justo nec condimentum', -81);
insert into product_sub_category (id, name, description, product_category_id) values (-312, 'Tony Thomerson', 'at turpis a pede posuere nonummy integer non', -340);
insert into product_sub_category (id, name, description, product_category_id) values (-313, 'Georgia Kibby', 'nisl duis ac nibh fusce', -191);
insert into product_sub_category (id, name, description, product_category_id) values (-314, 'Delmer Mohamed', 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus', -36);
insert into product_sub_category (id, name, description, product_category_id) values (-315, 'Tynan Munford', 'luctus rutrum nulla tellus in sagittis dui vel nisl duis', -245);
insert into product_sub_category (id, name, description, product_category_id) values (-316, 'Benjamin Abrehart', 'id ligula suspendisse ornare consequat lectus in', -60);
insert into product_sub_category (id, name, description, product_category_id) values (-317, 'Jeniece Tybalt', 'maecenas ut massa quis augue luctus tincidunt nulla', -393);
insert into product_sub_category (id, name, description, product_category_id) values (-318, 'Leeann Benzies', 'lobortis ligula sit amet eleifend', -454);
insert into product_sub_category (id, name, description, product_category_id) values (-319, 'Harriot Cossentine', 'sed tincidunt eu felis fusce posuere felis sed lacus', -255);
insert into product_sub_category (id, name, description, product_category_id) values (-320, 'Monique Battams', 'bibendum felis sed interdum venenatis turpis enim blandit mi in', -177);
insert into product_sub_category (id, name, description, product_category_id) values (-321, 'Cammi Gymlett', 'nam dui proin leo odio porttitor id consequat', -429);
insert into product_sub_category (id, name, description, product_category_id) values (-322, 'Perle Murrigan', 'metus arcu adipiscing molestie hendrerit', -148);
insert into product_sub_category (id, name, description, product_category_id) values (-323, 'Shannan Bairnsfather', 'sapien urna pretium nisl ut volutpat', -250);
insert into product_sub_category (id, name, description, product_category_id) values (-324, 'Bertie Garling', 'consectetuer eget rutrum at lorem', -173);
insert into product_sub_category (id, name, description, product_category_id) values (-325, 'Wylie Jansie', 'venenatis tristique fusce congue diam id ornare imperdiet sapien urna', -39);
insert into product_sub_category (id, name, description, product_category_id) values (-326, 'Raye Currall', 'mus vivamus vestibulum sagittis sapien cum sociis natoque', -67);
insert into product_sub_category (id, name, description, product_category_id) values (-327, 'Lorianna Semark', 'vestibulum ante ipsum primis in faucibus orci luctus et', -301);
insert into product_sub_category (id, name, description, product_category_id) values (-328, 'Broddy Klaff', 'tincidunt in leo maecenas pulvinar lobortis est phasellus', -154);
insert into product_sub_category (id, name, description, product_category_id) values (-329, 'Rickie Beckey', 'luctus et ultrices posuere cubilia curae mauris viverra diam vitae', -414);
insert into product_sub_category (id, name, description, product_category_id) values (-330, 'Yehudit Neeves', 'nunc vestibulum ante ipsum primis', -445);
insert into product_sub_category (id, name, description, product_category_id) values (-331, 'Jarrod Boustred', 'ligula vehicula consequat morbi a ipsum integer a', -184);
insert into product_sub_category (id, name, description, product_category_id) values (-332, 'Leelah Bunyard', 'vitae consectetuer eget rutrum at lorem integer', -103);
insert into product_sub_category (id, name, description, product_category_id) values (-333, 'Gaston Bruty', 'phasellus id sapien in sapien iaculis congue vivamus metus', -393);
insert into product_sub_category (id, name, description, product_category_id) values (-334, 'Randal Mattaus', 'id consequat in consequat ut nulla sed accumsan felis', -137);
insert into product_sub_category (id, name, description, product_category_id) values (-335, 'Bobbye Haggett', 'sit amet cursus id turpis integer', -315);
insert into product_sub_category (id, name, description, product_category_id) values (-336, 'Dewey MacCartair', 'nullam sit amet turpis elementum', -31);
insert into product_sub_category (id, name, description, product_category_id) values (-337, 'Caron Kingh', 'malesuada in imperdiet et commodo vulputate justo', -81);
insert into product_sub_category (id, name, description, product_category_id) values (-338, 'Donall Trobey', 'consectetuer eget rutrum at lorem integer tincidunt ante vel', -458);
insert into product_sub_category (id, name, description, product_category_id) values (-339, 'Tamera Sciusscietto', 'volutpat in congue etiam justo etiam pretium iaculis', -171);
insert into product_sub_category (id, name, description, product_category_id) values (-340, 'Alfred Tutsell', 'leo rhoncus sed vestibulum sit amet cursus', -169);
insert into product_sub_category (id, name, description, product_category_id) values (-341, 'Hakeem Millier', 'quisque erat eros viverra eget congue eget semper rutrum', -312);
insert into product_sub_category (id, name, description, product_category_id) values (-342, 'Lucilia Brecken', 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam', -406);
insert into product_sub_category (id, name, description, product_category_id) values (-343, 'Christine Dudley', 'faucibus orci luctus et ultrices posuere cubilia curae mauris', -394);
insert into product_sub_category (id, name, description, product_category_id) values (-344, 'Veronike Docherty', 'amet diam in magna bibendum imperdiet', -405);
insert into product_sub_category (id, name, description, product_category_id) values (-345, 'Sarena Littleton', 'quis orci nullam molestie nibh', -3);
insert into product_sub_category (id, name, description, product_category_id) values (-346, 'Marlin Glassborow', 'potenti cras in purus eu magna vulputate luctus cum sociis', -177);
insert into product_sub_category (id, name, description, product_category_id) values (-347, 'Linnie Keilty', 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', -114);
insert into product_sub_category (id, name, description, product_category_id) values (-348, 'Doralyn L''Episcopi', 'ante vel ipsum praesent blandit lacinia erat vestibulum sed', -335);
insert into product_sub_category (id, name, description, product_category_id) values (-349, 'Annabelle Lowis', 'ac enim in tempor turpis', -127);
insert into product_sub_category (id, name, description, product_category_id) values (-350, 'Thedric Clifford', 'posuere cubilia curae mauris viverra diam', -392);
insert into product_sub_category (id, name, description, product_category_id) values (-351, 'Ellary Robertazzi', 'donec quis orci eget orci vehicula', -299);
insert into product_sub_category (id, name, description, product_category_id) values (-352, 'Rutter Haxley', 'consequat varius integer ac leo pellentesque', -322);
insert into product_sub_category (id, name, description, product_category_id) values (-353, 'Laurent Libri', 'sed ante vivamus tortor duis mattis egestas', -249);
insert into product_sub_category (id, name, description, product_category_id) values (-354, 'Michelina Jantet', 'ullamcorper augue a suscipit nulla elit ac nulla sed', -124);
insert into product_sub_category (id, name, description, product_category_id) values (-355, 'Janel Cratere', 'ante nulla justo aliquam quis turpis eget elit', -311);
insert into product_sub_category (id, name, description, product_category_id) values (-356, 'Jon Gurery', 'sapien ut nunc vestibulum ante ipsum primis', -290);
insert into product_sub_category (id, name, description, product_category_id) values (-357, 'Goldi Ricciardello', 'ut erat curabitur gravida nisi at nibh', -345);
insert into product_sub_category (id, name, description, product_category_id) values (-358, 'Rhona Tramel', 'bibendum morbi non quam nec dui luctus rutrum nulla', -417);
insert into product_sub_category (id, name, description, product_category_id) values (-359, 'Gerri Scud', 'pede lobortis ligula sit amet eleifend pede', -288);
insert into product_sub_category (id, name, description, product_category_id) values (-360, 'Vince Haker', 'diam erat fermentum justo nec condimentum neque sapien', -279);
insert into product_sub_category (id, name, description, product_category_id) values (-361, 'Vassily Pitrelli', 'ligula pellentesque ultrices phasellus id sapien in', -360);
insert into product_sub_category (id, name, description, product_category_id) values (-362, 'Chaddie Sherbourne', 'in felis donec semper sapien', -58);
insert into product_sub_category (id, name, description, product_category_id) values (-363, 'Erna Belfrage', 'massa id nisl venenatis lacinia aenean sit amet justo', -228);
insert into product_sub_category (id, name, description, product_category_id) values (-364, 'Dyann Leverich', 'blandit lacinia erat vestibulum sed magna', -291);
insert into product_sub_category (id, name, description, product_category_id) values (-365, 'Petronella Millins', 'vulputate justo in blandit ultrices enim', -287);
insert into product_sub_category (id, name, description, product_category_id) values (-366, 'Loria Trenouth', 'posuere cubilia curae nulla dapibus dolor vel est donec', -418);
insert into product_sub_category (id, name, description, product_category_id) values (-367, 'Julie Searchfield', 'eu felis fusce posuere felis sed lacus morbi', -208);
insert into product_sub_category (id, name, description, product_category_id) values (-368, 'Rutherford Duce', 'sapien varius ut blandit non interdum', -285);
insert into product_sub_category (id, name, description, product_category_id) values (-369, 'Jolene Newcombe', 'gravida sem praesent id massa id nisl venenatis', -13);
insert into product_sub_category (id, name, description, product_category_id) values (-370, 'Aurora Raynton', 'diam cras pellentesque volutpat dui', -458);
insert into product_sub_category (id, name, description, product_category_id) values (-371, 'Henrie O''Hartagan', 'proin interdum mauris non ligula pellentesque ultrices phasellus id', -135);
insert into product_sub_category (id, name, description, product_category_id) values (-372, 'Wilie Menego', 'augue vestibulum rutrum rutrum neque aenean auctor gravida', -368);
insert into product_sub_category (id, name, description, product_category_id) values (-373, 'Pascale Yakolev', 'faucibus orci luctus et ultrices posuere cubilia curae', -257);
insert into product_sub_category (id, name, description, product_category_id) values (-374, 'Derby Hallett', 'sapien ut nunc vestibulum ante ipsum primis in faucibus orci', -21);
insert into product_sub_category (id, name, description, product_category_id) values (-375, 'Kial Hellicar', 'montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum', -438);
insert into product_sub_category (id, name, description, product_category_id) values (-376, 'Blayne Snassell', 'vel nulla eget eros elementum pellentesque', -89);
insert into product_sub_category (id, name, description, product_category_id) values (-377, 'Michail Percy', 'elementum in hac habitasse platea dictumst morbi vestibulum velit id', -83);
insert into product_sub_category (id, name, description, product_category_id) values (-378, 'Otha Cajkler', 'id justo sit amet sapien dignissim vestibulum vestibulum ante', -342);
insert into product_sub_category (id, name, description, product_category_id) values (-379, 'Diena D''Agostino', 'ultrices aliquet maecenas leo odio condimentum id', -354);
insert into product_sub_category (id, name, description, product_category_id) values (-380, 'Emmet Grimbleby', 'fringilla rhoncus mauris enim leo rhoncus', -454);
insert into product_sub_category (id, name, description, product_category_id) values (-381, 'Juanita Canet', 'vitae quam suspendisse potenti nullam porttitor lacus at turpis donec', -340);
insert into product_sub_category (id, name, description, product_category_id) values (-382, 'Maude Fusco', 'volutpat dui maecenas tristique est et tempus semper est quam', -10);
insert into product_sub_category (id, name, description, product_category_id) values (-383, 'Bernadine Jent', 'quis turpis eget elit sodales scelerisque mauris sit amet', -297);
insert into product_sub_category (id, name, description, product_category_id) values (-384, 'Jodi Pires', 'etiam justo etiam pretium iaculis justo', -127);
insert into product_sub_category (id, name, description, product_category_id) values (-385, 'Murry Lathy', 'integer ac leo pellentesque ultrices', -374);
insert into product_sub_category (id, name, description, product_category_id) values (-386, 'Renae Golbourn', 'aliquet at feugiat non pretium quis', -379);
insert into product_sub_category (id, name, description, product_category_id) values (-387, 'Bran Domesday', 'dui vel sem sed sagittis nam congue', -457);
insert into product_sub_category (id, name, description, product_category_id) values (-388, 'Bartlet Stonham', 'quisque id justo sit amet sapien dignissim', -260);
insert into product_sub_category (id, name, description, product_category_id) values (-389, 'Atlanta Handford', 'congue etiam justo etiam pretium iaculis justo in', -86);
insert into product_sub_category (id, name, description, product_category_id) values (-390, 'Jenine Veart', 'duis consequat dui nec nisi volutpat eleifend donec ut', -249);
insert into product_sub_category (id, name, description, product_category_id) values (-391, 'Joelle Longfoot', 'adipiscing elit proin risus praesent', -14);
insert into product_sub_category (id, name, description, product_category_id) values (-392, 'Gladys Toten', 'quis tortor id nulla ultrices', -297);
insert into product_sub_category (id, name, description, product_category_id) values (-393, 'Cece Comer', 'non pretium quis lectus suspendisse', -125);
insert into product_sub_category (id, name, description, product_category_id) values (-394, 'Kimberly Stuckow', 'nunc rhoncus dui vel sem sed sagittis', -424);
insert into product_sub_category (id, name, description, product_category_id) values (-395, 'Kelbee Dowbekin', 'eleifend quam a odio in hac habitasse platea dictumst maecenas', -168);
insert into product_sub_category (id, name, description, product_category_id) values (-396, 'Georgia Everitt', 'ac leo pellentesque ultrices mattis', -333);
insert into product_sub_category (id, name, description, product_category_id) values (-397, 'Mikey Houtby', 'eget vulputate ut ultrices vel augue vestibulum', -264);
insert into product_sub_category (id, name, description, product_category_id) values (-398, 'Elsworth Ferrari', 'ante vivamus tortor duis mattis egestas', -261);
insert into product_sub_category (id, name, description, product_category_id) values (-399, 'Anna-maria Chadwen', 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien', -263);
insert into product_sub_category (id, name, description, product_category_id) values (-400, 'Tandy Dybell', 'eleifend pede libero quis orci', -237);
insert into product_sub_category (id, name, description, product_category_id) values (-401, 'Dotti Deinert', 'ligula in lacus curabitur at', -329);
insert into product_sub_category (id, name, description, product_category_id) values (-402, 'Ronna Gyngyll', 'nonummy maecenas tincidunt lacus at', -386);
insert into product_sub_category (id, name, description, product_category_id) values (-403, 'Bibbie Conniam', 'feugiat et eros vestibulum ac', -464);
insert into product_sub_category (id, name, description, product_category_id) values (-404, 'Web Power', 'primis in faucibus orci luctus et ultrices', -237);
insert into product_sub_category (id, name, description, product_category_id) values (-405, 'Thain Ranshaw', 'orci vehicula condimentum curabitur in', -92);
insert into product_sub_category (id, name, description, product_category_id) values (-406, 'Marthena Lindemann', 'vulputate justo in blandit ultrices enim lorem ipsum dolor sit', -136);
insert into product_sub_category (id, name, description, product_category_id) values (-407, 'Kellby Pescud', 'sociis natoque penatibus et magnis', -329);
insert into product_sub_category (id, name, description, product_category_id) values (-408, 'Nertie Phorsby', 'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus', -436);
insert into product_sub_category (id, name, description, product_category_id) values (-409, 'Grover Holley', 'tincidunt lacus at velit vivamus vel nulla', -19);
insert into product_sub_category (id, name, description, product_category_id) values (-410, 'Husain O''Keaveny', 'justo etiam pretium iaculis justo', -405);
insert into product_sub_category (id, name, description, product_category_id) values (-411, 'Starla Dymocke', 'nulla integer pede justo lacinia eget tincidunt', -429);
insert into product_sub_category (id, name, description, product_category_id) values (-412, 'Dorelle Petegrew', 'neque vestibulum eget vulputate ut', -162);
insert into product_sub_category (id, name, description, product_category_id) values (-413, 'Bertha Oakden', 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', -330);
insert into product_sub_category (id, name, description, product_category_id) values (-414, 'Emelen Gillease', 'odio odio elementum eu interdum eu tincidunt in', -453);
insert into product_sub_category (id, name, description, product_category_id) values (-415, 'Laural Ruggen', 'at nibh in hac habitasse platea dictumst aliquam augue quam', -318);
insert into product_sub_category (id, name, description, product_category_id) values (-416, 'Gilli Rabbage', 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum', -382);
insert into product_sub_category (id, name, description, product_category_id) values (-417, 'Andee MacAndrew', 'morbi a ipsum integer a nibh in', -346);
insert into product_sub_category (id, name, description, product_category_id) values (-418, 'Gustavus Halt', 'adipiscing elit proin risus praesent', -64);
insert into product_sub_category (id, name, description, product_category_id) values (-419, 'Elsa Chessill', 'nisl duis ac nibh fusce lacus', -492);
insert into product_sub_category (id, name, description, product_category_id) values (-420, 'Currey Ulster', 'molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque', -117);
insert into product_sub_category (id, name, description, product_category_id) values (-421, 'Waylon Wasmer', 'vel nulla eget eros elementum pellentesque quisque porta', -386);
insert into product_sub_category (id, name, description, product_category_id) values (-422, 'Herschel Yurinov', 'rutrum at lorem integer tincidunt ante', -163);
insert into product_sub_category (id, name, description, product_category_id) values (-423, 'Anet Wooffinden', 'tempor convallis nulla neque libero convallis eget', -134);
insert into product_sub_category (id, name, description, product_category_id) values (-424, 'Ivie Wellan', 'nec molestie sed justo pellentesque viverra', -6);
insert into product_sub_category (id, name, description, product_category_id) values (-425, 'Orsa Cromblehome', 'amet cursus id turpis integer aliquet massa id lobortis convallis', -475);
insert into product_sub_category (id, name, description, product_category_id) values (-426, 'Husain Hitter', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices', -212);
insert into product_sub_category (id, name, description, product_category_id) values (-427, 'Dayna Carruth', 'turpis integer aliquet massa id lobortis convallis tortor risus', -371);
insert into product_sub_category (id, name, description, product_category_id) values (-428, 'Tony Crossman', 'massa quis augue luctus tincidunt nulla', -193);
insert into product_sub_category (id, name, description, product_category_id) values (-429, 'Remy Balhatchet', 'integer tincidunt ante vel ipsum praesent blandit lacinia', -59);
insert into product_sub_category (id, name, description, product_category_id) values (-430, 'Myrtie Warters', 'sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in', -440);
insert into product_sub_category (id, name, description, product_category_id) values (-431, 'Cherie Heinle', 'non mi integer ac neque duis', -220);
insert into product_sub_category (id, name, description, product_category_id) values (-432, 'Malvin Pranger', 'proin risus praesent lectus vestibulum quam', -103);
insert into product_sub_category (id, name, description, product_category_id) values (-433, 'Judah Asling', 'eu sapien cursus vestibulum proin', -214);
insert into product_sub_category (id, name, description, product_category_id) values (-434, 'Willow Whipple', 'volutpat erat quisque erat eros viverra eget', -4);
insert into product_sub_category (id, name, description, product_category_id) values (-435, 'Atlanta Skill', 'mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum', -92);
insert into product_sub_category (id, name, description, product_category_id) values (-436, 'Erika Neller', 'morbi quis tortor id nulla ultrices', -469);
insert into product_sub_category (id, name, description, product_category_id) values (-437, 'Zechariah Hapgood', 'at lorem integer tincidunt ante vel', -208);
insert into product_sub_category (id, name, description, product_category_id) values (-438, 'Iago Harnott', 'at lorem integer tincidunt ante', -443);
insert into product_sub_category (id, name, description, product_category_id) values (-439, 'Rinaldo Pinnigar', 'ligula nec sem duis aliquam convallis nunc proin at turpis', -118);
insert into product_sub_category (id, name, description, product_category_id) values (-440, 'Thibaut Peachey', 'diam in magna bibendum imperdiet nullam orci pede venenatis non', -352);
insert into product_sub_category (id, name, description, product_category_id) values (-441, 'Juliann Dunsmore', 'molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque', -354);
insert into product_sub_category (id, name, description, product_category_id) values (-442, 'Ollie Dudek', 'mauris ullamcorper purus sit amet nulla quisque', -356);
insert into product_sub_category (id, name, description, product_category_id) values (-443, 'Janene Callard', 'justo maecenas rhoncus aliquam lacus morbi', -151);
insert into product_sub_category (id, name, description, product_category_id) values (-444, 'Jay Greguol', 'nisi at nibh in hac habitasse platea dictumst', -205);
insert into product_sub_category (id, name, description, product_category_id) values (-445, 'Bob Kleis', 'consequat varius integer ac leo pellentesque ultrices mattis', -372);
insert into product_sub_category (id, name, description, product_category_id) values (-446, 'Alvin Follin', 'lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed', -282);
insert into product_sub_category (id, name, description, product_category_id) values (-447, 'Della Haw', 'massa quis augue luctus tincidunt', -274);
insert into product_sub_category (id, name, description, product_category_id) values (-448, 'Fair Balthasar', 'ut odio cras mi pede malesuada in imperdiet et', -394);
insert into product_sub_category (id, name, description, product_category_id) values (-449, 'Rubina Dacey', 'in tempus sit amet sem fusce consequat nulla nisl nunc', -263);
insert into product_sub_category (id, name, description, product_category_id) values (-450, 'Waylon Adaway', 'lacinia eget tincidunt eget tempus vel pede', -477);
insert into product_sub_category (id, name, description, product_category_id) values (-451, 'Shanna Veal', 'arcu sed augue aliquam erat volutpat in congue etiam justo', -157);
insert into product_sub_category (id, name, description, product_category_id) values (-452, 'Nicolle Casel', 'ipsum primis in faucibus orci luctus et', -80);
insert into product_sub_category (id, name, description, product_category_id) values (-453, 'Lodovico Curry', 'quisque erat eros viverra eget congue eget semper', -213);
insert into product_sub_category (id, name, description, product_category_id) values (-454, 'Marja Brinded', 'semper porta volutpat quam pede lobortis ligula sit amet eleifend', -189);
insert into product_sub_category (id, name, description, product_category_id) values (-455, 'Sergent Dowdle', 'lectus in quam fringilla rhoncus mauris enim', -100);
insert into product_sub_category (id, name, description, product_category_id) values (-456, 'Leta Gallafant', 'commodo placerat praesent blandit nam nulla integer pede', -337);
insert into product_sub_category (id, name, description, product_category_id) values (-457, 'Georgy Clemonts', 'donec pharetra magna vestibulum aliquet', -421);
insert into product_sub_category (id, name, description, product_category_id) values (-458, 'Gilberto Bon', 'eget elit sodales scelerisque mauris', -2);
insert into product_sub_category (id, name, description, product_category_id) values (-459, 'Angelica Hoys', 'pede ullamcorper augue a suscipit', -23);
insert into product_sub_category (id, name, description, product_category_id) values (-460, 'Judy Schust', 'nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque', -145);
insert into product_sub_category (id, name, description, product_category_id) values (-461, 'Graham Calliss', 'ipsum praesent blandit lacinia erat vestibulum sed magna at nunc', -345);
insert into product_sub_category (id, name, description, product_category_id) values (-462, 'Roobbie Axcell', 'tempus semper est quam pharetra', -320);
insert into product_sub_category (id, name, description, product_category_id) values (-463, 'Bellanca Seakes', 'ultrices erat tortor sollicitudin mi sit amet lobortis', -23);
insert into product_sub_category (id, name, description, product_category_id) values (-464, 'Vikky Abramovitch', 'curabitur in libero ut massa volutpat convallis morbi', -25);
insert into product_sub_category (id, name, description, product_category_id) values (-465, 'Silvan Pringer', 'proin leo odio porttitor id consequat in consequat ut', -354);
insert into product_sub_category (id, name, description, product_category_id) values (-466, 'Celestina Holdey', 'id nulla ultrices aliquet maecenas leo', -281);
insert into product_sub_category (id, name, description, product_category_id) values (-467, 'Tanney Lowseley', 'diam vitae quam suspendisse potenti nullam porttitor lacus at', -207);
insert into product_sub_category (id, name, description, product_category_id) values (-468, 'Tori Keyte', 'turpis donec posuere metus vitae ipsum', -86);
insert into product_sub_category (id, name, description, product_category_id) values (-469, 'Alane Low', 'hendrerit at vulputate vitae nisl aenean lectus', -179);
insert into product_sub_category (id, name, description, product_category_id) values (-470, 'Thadeus Esch', 'in faucibus orci luctus et ultrices', -179);
insert into product_sub_category (id, name, description, product_category_id) values (-471, 'Chanda McCleverty', 'placerat ante nulla justo aliquam quis turpis eget elit', -58);
insert into product_sub_category (id, name, description, product_category_id) values (-472, 'Domini Chaperling', 'suspendisse accumsan tortor quis turpis sed', -214);
insert into product_sub_category (id, name, description, product_category_id) values (-473, 'Johna Dell Casa', 'ultrices aliquet maecenas leo odio condimentum id', -347);
insert into product_sub_category (id, name, description, product_category_id) values (-474, 'Rivalee Gravatt', 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum', -492);
insert into product_sub_category (id, name, description, product_category_id) values (-475, 'Sancho Burmaster', 'varius nulla facilisi cras non velit nec nisi', -44);
insert into product_sub_category (id, name, description, product_category_id) values (-476, 'Franciskus Oubridge', 'mauris lacinia sapien quis libero nullam sit', -392);
insert into product_sub_category (id, name, description, product_category_id) values (-477, 'Justinn Hutchens', 'montes nascetur ridiculus mus etiam', -139);
insert into product_sub_category (id, name, description, product_category_id) values (-478, 'Cristina Blennerhassett', 'sit amet turpis elementum ligula vehicula consequat morbi', -407);
insert into product_sub_category (id, name, description, product_category_id) values (-479, 'Fiona Fransseni', 'non pretium quis lectus suspendisse potenti in eleifend quam a', -435);
insert into product_sub_category (id, name, description, product_category_id) values (-480, 'Emmalee Dimmack', 'consequat ut nulla sed accumsan felis ut at', -106);
insert into product_sub_category (id, name, description, product_category_id) values (-481, 'Lindy Epilet', 'id turpis integer aliquet massa id', -168);
insert into product_sub_category (id, name, description, product_category_id) values (-482, 'Vicki Brinkley', 'pede morbi porttitor lorem id ligula suspendisse', -330);
insert into product_sub_category (id, name, description, product_category_id) values (-483, 'Mirabel Mowen', 'dictumst maecenas ut massa quis augue luctus tincidunt nulla', -244);
insert into product_sub_category (id, name, description, product_category_id) values (-484, 'Marje Learoid', 'molestie sed justo pellentesque viverra', -65);
insert into product_sub_category (id, name, description, product_category_id) values (-485, 'Sharline Vakhonin', 'maecenas tincidunt lacus at velit vivamus vel', -45);
insert into product_sub_category (id, name, description, product_category_id) values (-486, 'Chancey Arnowitz', 'quis orci nullam molestie nibh in lectus pellentesque at nulla', -174);
insert into product_sub_category (id, name, description, product_category_id) values (-487, 'Darby Ricca', 'et commodo vulputate justo in blandit ultrices', -158);
insert into product_sub_category (id, name, description, product_category_id) values (-488, 'Elsbeth Gaspard', 'mauris non ligula pellentesque ultrices phasellus', -80);
insert into product_sub_category (id, name, description, product_category_id) values (-489, 'Nichole Davage', 'eget semper rutrum nulla nunc purus', -186);
insert into product_sub_category (id, name, description, product_category_id) values (-490, 'Gibbie Frammingham', 'quis augue luctus tincidunt nulla mollis molestie lorem', -497);
insert into product_sub_category (id, name, description, product_category_id) values (-491, 'Luigi Scrammage', 'eu sapien cursus vestibulum proin', -262);
insert into product_sub_category (id, name, description, product_category_id) values (-492, 'Moses Drei', 'elementum ligula vehicula consequat morbi a ipsum', -369);
insert into product_sub_category (id, name, description, product_category_id) values (-493, 'Gawen Wakefield', 'et ultrices posuere cubilia curae nulla', -108);
insert into product_sub_category (id, name, description, product_category_id) values (-494, 'Manny Bagby', 'diam nam tristique tortor eu', -61);
insert into product_sub_category (id, name, description, product_category_id) values (-495, 'Danella McClinton', 'metus vitae ipsum aliquam non mauris morbi', -300);
insert into product_sub_category (id, name, description, product_category_id) values (-496, 'Bertram Pinkie', 'id consequat in consequat ut nulla sed', -356);
insert into product_sub_category (id, name, description, product_category_id) values (-497, 'Brittany Rosina', 'quis justo maecenas rhoncus aliquam lacus morbi', -386);
insert into product_sub_category (id, name, description, product_category_id) values (-498, 'Merla Conibear', 'sem duis aliquam convallis nunc proin at', -38);
insert into product_sub_category (id, name, description, product_category_id) values (-499, 'Lew Cheale', 'tempus vivamus in felis eu sapien cursus', -353);
insert into product_sub_category (id, name, description, product_category_id) values (-500, 'Keely Wilacot', 'nunc rhoncus dui vel sem sed sagittis', -256);
